CREATE UNIQUE NONCLUSTERED INDEX [IX_FORM_ROLE]
    ON [SECURITY].[FORM_ROLE]([FORM_ROLE_FORM_ID] ASC, [FORM_ROLE_ROLE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

