CREATE TABLE [SETUP].[CATEGORY] (
    [CATEGORY_ID]           INT             IDENTITY (1, 1) NOT NULL,
    [CATEGORY_NAME]         NVARCHAR (500)  NOT NULL,
    [CATEGORY_DESCRIPTION]  NVARCHAR (1000) NOT NULL,
    [CATEGORY_MODULE_ID]    INT             NOT NULL,
    [CATEGORY_IS_DELETED]   BIT             NOT NULL,
    [CATEGORY_PORTAL_ID]    INT             NOT NULL,
    [CATEGORY_LANGUAGE_ID]  INT             NOT NULL,
    [CATEGORY_CREATION_DAY] INT             NOT NULL,
    [CATEGORY_CREATION_SEC] INT             NOT NULL,
    [CATEGORY_PARENT_ID]    INT             NOT NULL,
    [CATEGORY_ORDER]        INT             NOT NULL,
    [CATEGORY_CREATED_BY]   INT             NOT NULL,
    [CATEGORY_IMAGE]        NVARCHAR (500)  NOT NULL
);

