CREATE TABLE [SETUP].[CMSCONTROL] (
    [CMSCONTROL_ID]                INT             IDENTITY (1, 1) NOT NULL,
    [CMSCONTROL_NAME]              NVARCHAR (500)  NOT NULL,
    [CMSCONTROL_DESCRIPTION]       NVARCHAR (1000) NOT NULL,
    [CMSCONTROL_USER_CONTROL_PATH] NVARCHAR (1000) NOT NULL,
    [CMSCONTROL_IS_DELETED]        BIT             NOT NULL,
    [CMSCONTROL_CREATION_DAY]      INT             NOT NULL,
    [CMSCONTROL_CREATION_SEC]      INT             NOT NULL,
    [CMSCONTROL_MODULE_ID]         INT             NOT NULL,
    [CMSCONTROL_CREATED_BY]        INT             NOT NULL
);

