CREATE TABLE [SETUP].[HTMLBLOCK] (
    [HTMLBLOCK_ID]           INT            IDENTITY (1, 1) NOT NULL,
    [HTMLBLOCK_NAME]         NVARCHAR (500) NOT NULL,
    [HTMLBLOCK_DETAILS]      NTEXT          NOT NULL,
    [HTMLBLOCK_IS_DELETED]   BIT            NOT NULL,
    [HTMLBLOCK_PORTAL_ID]    INT            NOT NULL,
    [HTMLBLOCK_LANGUAGE_ID]  INT            NOT NULL,
    [HTMLBLOCK_CREATION_DAY] INT            NOT NULL,
    [HTMLBLOCK_CREATION_SEC] INT            NOT NULL,
    [HTMLBLOCK_CREATED_BY]   INT            NOT NULL
);

