CREATE TABLE [SETUP].[LANGUAGE] (
    [LANGUAGE_ID]      INT            IDENTITY (1, 1) NOT NULL,
    [LANGUAGE_NAME]    NVARCHAR (100) NOT NULL,
    [LANGUAGE_CULTURE] NVARCHAR (50)  NOT NULL,
    [LANGUAGE_IMAGE]   NVARCHAR (500) NOT NULL
);

