CREATE TABLE [SETUP].[MODULE] (
    [MODULE_ID]           INT             IDENTITY (1, 1) NOT NULL,
    [MODULE_NAME]         NVARCHAR (500)  NOT NULL,
    [MODULE_DESCRIPTION]  NVARCHAR (1000) NOT NULL,
    [MODULE_IMAGE]        NVARCHAR (500)  NOT NULL,
    [MODULE_IS_DELETED]   BIT             NOT NULL,
    [MODULE_CREATION_DAY] INT             NOT NULL,
    [MODULE_CREATION_SEC] INT             NOT NULL,
    [MODULE_CREATED_BY]   INT             NOT NULL,
    [MODULE_PARENT_ID]    INT             NOT NULL
);

