CREATE TABLE [SETUP].[PAGE] (
    [PAGE_ID]           INT             IDENTITY (1, 1) NOT NULL,
    [PAGE_CREATION_DAY] INT             NOT NULL,
    [PAGE_CREATION_SEC] INT             NOT NULL,
    [PAGE_DESCRIPTION]  NVARCHAR (1000) NOT NULL,
    [PAGE_DETAILS]      NTEXT           NOT NULL,
    [PAGE_ICON]         NVARCHAR (500)  NOT NULL,
    [PAGE_IS_DELETED]   BIT             NOT NULL,
    [PAGE_KEYWORDS]     NVARCHAR (1000) NOT NULL,
    [PAGE_LANGUAGE_ID]  INT             NOT NULL,
    [PAGE_NAME]         NVARCHAR (500)  NOT NULL,
    [PAGE_TYPE]         INT             NOT NULL,
    [PAGE_PORTAL_ID]    INT             NOT NULL,
    [PAGE_SEO_NAME]     NVARCHAR (1000) NOT NULL,
    [PAGE_TITLE]        NVARCHAR (500)  NOT NULL,
    [PAGE_TEMPLATE_ID]  INT             NOT NULL,
    [PAGE_CREATED_BY]   INT             NOT NULL
);

