CREATE TABLE [SETUP].[PUBLISH] (
    [PUBLISH_ID]          INT IDENTITY (1, 1) NOT NULL,
    [PUBLISH_MODULE_ID]   INT NOT NULL,
    [PUBLISH_OBJECT_ID]   INT NOT NULL,
    [PUBLISH_TYPE_ID]     INT NOT NULL,
    [PUBLISH_FROM_DAY]    INT NOT NULL,
    [PUBLISH_FROM_SEC]    INT NOT NULL,
    [PUBLISH_TO_DAY]      INT NOT NULL,
    [PUBLISH_TO_SEC]      INT NOT NULL,
    [PUBLISH_CREATED_BY]  INT NOT NULL,
    [PUBLISH_PORTAL_ID]   INT NOT NULL,
    [PUBLISH_LANGUAGE_ID] INT NOT NULL
);

