CREATE TABLE [SETUP].[TEMPLATE] (
    [TEMPLATE_ID]           INT             IDENTITY (1, 1) NOT NULL,
    [TEMPLATE_CREATION_DAY] INT             NOT NULL,
    [TEMPLATE_CREATION_SEC] INT             NOT NULL,
    [TEMPLATE_DESCRIPTION]  NVARCHAR (1000) NOT NULL,
    [TEMPLATE_DETAILS]      NTEXT           NOT NULL,
    [TEMPLATE_IMAGE]        NVARCHAR (500)  NOT NULL,
    [TEMPLATE_IS_DELETED]   BIT             NOT NULL,
    [TEMPLATE_LANGUAGE_ID]  INT             NOT NULL,
    [TEMPLATE_NAME]         NVARCHAR (500)  NOT NULL,
    [TEMPLATE_PORTAL_ID]    INT             NOT NULL,
    [TEMPLATE_CREATED_BY]   INT             NULL
);

