CREATE TABLE [SETUP].[XSLTEMPLATE] (
    [XSLTEMPLATE_ID]           INT             IDENTITY (1, 1) NOT NULL,
    [XSLTEMPLATE_NAME]         NVARCHAR (500)  NOT NULL,
    [XSLTEMPLATE_DESCRIPTION]  NVARCHAR (1000) NOT NULL,
    [XSLTEMPLATE_DETAILS]      NTEXT           NOT NULL,
    [XSLTEMPLATE_MODULE_ID]    INT             NOT NULL,
    [XSLTEMPLATE_IS_DELETED]   BIT             NOT NULL,
    [XSLTEMPLATE_PORTAL_ID]    INT             NOT NULL,
    [XSLTEMPLATE_LANGUAGE_ID]  INT             NOT NULL,
    [XSLTEMPLATE_CREATION_DAY] INT             NOT NULL,
    [XSLTEMPLATE_CREATION_SEC] INT             NOT NULL,
    [XSLTEMPLATE_CREATED_BY]   INT             NOT NULL
);

