CREATE PROCEDURE [ECOMMERCE].[AttributeAdd]
	@P_ATTRIBUTE_ID int output,
	@P_ATTRIBUTE_GROUP_ID int,
	@P_ATTRIBUTE_PORTAL_ID int,
	@P_ATTRIBUTE_NAME NVARCHAR(500),
	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
    
AS
BEGIN
	SET NOCOUNT ON;
	
	DECLARE @Transaction VARCHAR(100);
	SELECT @Transaction = 'Transaction';

	BEGIN TRANSACTION @Transaction;

	INSERT INTO [ECOMMERCE].[ATTRIBUTE]
		(
		[ATTRIBUTE_GROUP_ID],
		[ATTRIBUTE_PORTAL_ID]
		)
	VALUES
		(
		@P_ATTRIBUTE_GROUP_ID,
		@P_ATTRIBUTE_PORTAL_ID
		)
		
		set @P_ATTRIBUTE_ID=SCOPE_IDENTITY()
		
		INSERT INTO [ECOMMERCE].[ECOMMERCE_LANGUAGE]
			(
				[ECO_LAN_OBJ_ID],
				[ECO_LAN_MODULE_ID],
				[ECO_LAN_LAN_ID],		
				[ECO_LAN_NAME]	
			)
			VALUES
			(
				@P_ATTRIBUTE_ID,
				@P_MODULE_ID,
				@P_ECO_LAN_LAN_ID,
				@P_ATTRIBUTE_NAME
			)
			
			IF @@ERROR != 0
            BEGIN 
                  ROLLBACK TRANSACTION
                  RETURN
            END

			COMMIT TRANSACTION @Transaction

			
END
