CREATE PROCEDURE [ECOMMERCE].[AttributeGetAll]
	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
AS
BEGIN
	SET NOCOUNT ON;
	SELECT
			A.[ATTRIBUTE_ID],
			A.[ATTRIBUTE_GROUP_ID],
			A.[ATTRIBUTE_PORTAL_ID],
			A.[ATTRIBUTE_IS_DELETED],
			EL.[ECO_LAN_LAN_ID],
			EL.[ECO_LAN_NAME],
			EL.[ECO_LAN_OBJ_ID]
	 FROM  [ECOMMERCE].[ATTRIBUTE] AS A
			LEFT OUTER JOIN
		   ECOMMERCE.ECOMMERCE_LANGUAGE AS EL
	 ON	
				EL.[ECO_LAN_OBJ_ID] = A.[ATTRIBUTE_ID]
			AND
				EL.[ECO_LAN_MODULE_ID] = @P_MODULE_ID
			AND
				EL.[ECO_LAN_LAN_ID] = @P_ECO_LAN_LAN_ID
		WHERE A.[ATTRIBUTE_IS_DELETED]=0
	END
