CREATE PROCEDURE [ECOMMERCE].[AttributeAddOtherLang]
	@P_ATTRIBUTE_ID int,
	@P_ATTRIBUTE_NAME NVARCHAR(500),
	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
    
AS
BEGIN
	
		INSERT INTO [ECOMMERCE].[ECOMMERCE_LANGUAGE]
			(
				[ECO_LAN_OBJ_ID],
				[ECO_LAN_MODULE_ID],
				[ECO_LAN_LAN_ID],		
				[ECO_LAN_NAME]	
			)
			VALUES
			(
				@P_ATTRIBUTE_ID,
				@P_MODULE_ID,
				@P_ECO_LAN_LAN_ID,
				@P_ATTRIBUTE_NAME
			)
			
END
