CREATE PROCEDURE [ECOMMERCE].[CatalogGetByProductID]
	@P_PRODUCT_ID INT,
	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT,
	@P_CATALOG_PORTAL_ID int
    
AS
BEGIN
	SET NOCOUNT ON;
	select
				C.[CATALOG_ID],
				C.[CATALOG_PARENT_CATALOG_ID],
				C.[CATALOG_ORDER],
				C.[CATALOG_IS_PUBLISHED],
				EL.[ECO_LAN_NAME]
				
	 from  
		[ECOMMERCE].[CATALOG] AS C
			INNER JOIN 
		[ECOMMERCE].[PRODUCT_CATALOG] AS PC
		ON
		PC.[CATALOG_ID] =C.[CATALOG_ID] 
			AND 
		PC.[PRODUCT_ID] = @P_PRODUCT_ID
			LEFT OUTER JOIN 
		[ECOMMERCE].[ECOMMERCE_LANGUAGE] AS EL
		ON 
		EL.[ECO_LAN_OBJ_ID] = C.[CATALOG_ID]
			AND
		EL.[ECO_LAN_MODULE_ID] = @P_MODULE_ID
			AND
		EL.[ECO_LAN_LAN_ID] = @P_ECO_LAN_LAN_ID
	
	WHERE
		C.[CATALOG_IS_DELETED] = 0 and [CATALOG_PORTAL_ID]= @P_CATALOG_PORTAL_ID
		order by C.[CATALOG_ID],pc.PRODUCT_ORDER
END
