CREATE PROCEDURE [ECOMMERCE].[CatalogAddOtherLang]
		@P_CATALOG_ID int ,
		
		@P_ECO_LAN_NAME nvarchar(500),
		@P_ECO_LAN_DESC nvarchar(500),
		@P_ECO_LAN_NAME2 nvarchar(500),
		@P_ECO_LAN_DESC2 nvarchar(500),
		@P_ECO_LAN_KEYWORD nvarchar(500),
		@P_MODULE_ID INT,
		@P_ECO_LAN_LAN_ID INT	
    
AS
BEGIN
	SET NOCOUNT ON;
	
	INSERT INTO [ECOMMERCE].[ECOMMERCE_LANGUAGE]
			(
				[ECO_LAN_OBJ_ID],
				[ECO_LAN_MODULE_ID],
				[ECO_LAN_LAN_ID],
				[ECO_LAN_NAME],
				[ECO_LAN_DESC],
				[ECO_LAN_NAME2],
				[ECO_LAN_DESC2],
				[ECO_LAN_KEYWORD]
			)
			VALUES
			(
				@P_CATALOG_ID,
				@P_MODULE_ID,
				@P_ECO_LAN_LAN_ID,
				@P_ECO_LAN_NAME,
				@P_ECO_LAN_DESC ,
				@P_ECO_LAN_NAME2 ,
				@P_ECO_LAN_DESC2 ,
				@P_ECO_LAN_KEYWORD
			)
END
