CREATE PROCEDURE [ECOMMERCE].[CatalogGetByID]
	@P_CATALOG_ID int ,	
    @P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
AS
BEGIN
	SET NOCOUNT ON;
	select
				C.[CATALOG_ID],
				C.[CATALOG_IS_DISPLAYED],
				C.[CATALOG_IS_GALLERY_ONLY],
				C.[CATALOG_PARENT_CATALOG_ID],
				C.[CATALOG_IS_DELETED],
				C.[CATALOG_PORTAL_ID],
				C.[CATALOG_ORDER],
				C.[CATALOG_IS_PUBLISHED],
				EL.[ECO_LAN_LAN_ID],
				EL.[ECO_LAN_NAME],
				EL.[ECO_LAN_DESC],
				EL.[ECO_LAN_NAME2],
				EL.[ECO_LAN_DESC2],
				EL.[ECO_LAN_KEYWORD] 
	 from  
		[ECOMMERCE].[CATALOG] AS C
			LEFT OUTER JOIN 
		[ECOMMERCE].[ECOMMERCE_LANGUAGE] AS EL
		ON 
		EL.[ECO_LAN_OBJ_ID] = C.[CATALOG_ID]
			AND
		EL.[ECO_LAN_MODULE_ID] = @P_MODULE_ID
			AND
		EL.[ECO_LAN_LAN_ID] = @P_ECO_LAN_LAN_ID
	
	where 
		CATALOG_ID = @P_CATALOG_ID
		
	
END
