CREATE PROCEDURE [ECOMMERCE].[CatalogImageAdd]
	
		@P_CATALOG_IMAGE_ID int output,
		@P_CATALOG_ID int,
		@P_CATALOG_IMAGE_NAME nvarchar(500),
		@P_CATALOG_IMAGE_IS_COVER_IMAGE bit
    
AS
BEGIN
	SET NOCOUNT ON;

	insert into [ECOMMERCE].[CATALOG_IMAGE]
	(
		CATALOG_ID,
		CATALOG_IMAGE_NAME,
		CATALOG_IMAGE_IS_COVER_IMAGE
	)
	values
	(
		@P_CATALOG_ID,
		@P_CATALOG_IMAGE_NAME,
		@P_CATALOG_IMAGE_IS_COVER_IMAGE
	)
	
	set @P_CATALOG_IMAGE_ID = SCOPE_IDENTITY()
	
END
