CREATE PROCEDURE [ECOMMERCE].[CombinationImageDelete]

	@P_COMBINATION_IMAGE_ID	int,
	@P_COMBINATION_ID	int	
    
AS
BEGIN
	SET NOCOUNT ON;
	
	delete from  
	  [ECOMMERCE].[COMBINATION_IMAGE]
		where
		 COMBINATION_IMAGE_ID = @P_COMBINATION_IMAGE_ID
		 and COMBINATION_ID = @P_COMBINATION_ID
	
END
