CREATE PROCEDURE [ECOMMERCE].[CombinationAttributeDelete]

	@P_COMBINATION_ID	int,
	@P_ATTRIBUTE_ID	int	
    
AS
BEGIN
	SET NOCOUNT ON;
	
	delete from
	  [ECOMMERCE].[COMBINATION_ATTRIBUTE]
		where
			[COMBINATION_ID] = @P_COMBINATION_ID
			and
			[ATTRIBUTE_ID] = @P_ATTRIBUTE_ID
	
END
