CREATE PROCEDURE [ECOMMERCE].[CombinationProductUpdate]

	@P_COMBINATION_ID	int,
	@P_COMBINATION_PRODUCT_ID	int,
	@P_COMBINATION_PRODUCT_REFERENCE	nvarchar(500),
	@P_COMBINATION_PRODUCT_EAN13	nvarchar(500),
	@P_COMBINATION_PRODUCT_UPC	nvarchar(500),
	@P_COMBINATION_PRODUCT_SUPPLIER_REFERENCE	int,
	@P_COMBINATION_PRODUCT_WHOLESALE_PRICE	decimal,
	@P_COMBINATION_PRODUCT_IMPACT_ON_PRICE	int,
	@P_COMBINATION_PRODUCT_IMPACT_ON_WEIGHT	int,
	@P_COMBINATION_PRODUCT_INITIAL_STOCK	int	,
	@P_COMBINATION_PRODUCT_MINIMUM_QUANTITY	int,
	@P_COMBINATION_PRODUCT_IS_DEFAULT	bit	,
	@P_COMBINATION_PRODUCT_COLOR	nvarchar(500),
	
	@P_COMBINATION_PRODUCT_LOCATION NVARCHAR(500),
	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
    
	AS
	BEGIN
		SET NOCOUNT ON;
	
	DECLARE @Transaction VARCHAR(100);
	SELECT @Transaction = 'Transaction';

	BEGIN TRANSACTION @Transaction;

	update [ECOMMERCE].[COMBINATION_PRODUCT]
		set
			[COMBINATION_PRODUCT_ID] = @P_COMBINATION_PRODUCT_ID,
			[COMBINATION_PRODUCT_REFERENCE] = @P_COMBINATION_PRODUCT_REFERENCE,
			[COMBINATION_PRODUCT_EAN13] = @P_COMBINATION_PRODUCT_EAN13,
			[COMBINATION_PRODUCT_UPC] = @P_COMBINATION_PRODUCT_UPC,
			[COMBINATION_PRODUCT_SUPPLIER_REFERENCE] = @P_COMBINATION_PRODUCT_SUPPLIER_REFERENCE,
			[COMBINATION_PRODUCT_WHOLESALE_PRICE] = @P_COMBINATION_PRODUCT_WHOLESALE_PRICE,
			[COMBINATION_PRODUCT_IMPACT_ON_PRICE] = @P_COMBINATION_PRODUCT_IMPACT_ON_PRICE,
			[COMBINATION_PRODUCT_IMPACT_ON_WEIGHT] = @P_COMBINATION_PRODUCT_IMPACT_ON_WEIGHT,
			[COMBINATION_PRODUCT_INITIAL_STOCK] = @P_COMBINATION_PRODUCT_INITIAL_STOCK,
			[COMBINATION_PRODUCT_MINIMUM_QUANTITY] = @P_COMBINATION_PRODUCT_MINIMUM_QUANTITY,
			[COMBINATION_PRODUCT_IS_DEFAULT] = @P_COMBINATION_PRODUCT_IS_DEFAULT,
			[COMBINATION_PRODUCT_COLOR] = @P_COMBINATION_PRODUCT_COLOR
		
		where [COMBINATION_ID] = @P_COMBINATION_ID
		
		update [ECOMMERCE].[ECOMMERCE_LANGUAGE]
			set
				[ECO_LAN_NAME] = @P_COMBINATION_PRODUCT_LOCATION
			
			WHERE 
			    [ECO_LAN_OBJ_ID] = @P_COMBINATION_ID
			    AND
				[ECO_LAN_MODULE_ID] = @P_MODULE_ID
				AND
				[ECO_LAN_LAN_ID]  = @P_ECO_LAN_LAN_ID 
				
			IF @@ERROR != 0
            BEGIN 
                  ROLLBACK TRANSACTION
                  RETURN
            END

			COMMIT TRANSACTION @Transaction

			
END
