CREATE PROCEDURE [ECOMMERCE].[FeatureAdd]
	@P_FEATURE_ID INT OUTPUT,
	@P_FEATURE_PORTAL_ID INT,
	
	@P_FEATURE_NAME NVARCHAR(500),
	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
    
AS
BEGIN
	SET NOCOUNT ON;
	
	DECLARE @Transaction VARCHAR(100);
	SELECT @Transaction = 'Transaction';

	BEGIN TRANSACTION @Transaction;
	
	INSERT INTO [ECOMMERCE].[Feature]
		(
		[FEATURE_PORTAL_ID]
		)
	VALUES
		(
		@P_FEATURE_PORTAL_ID
		)
		
		set @P_FEATURE_ID=SCOPE_IDENTITY()
		
		INSERT INTO [ECOMMERCE].[ECOMMERCE_LANGUAGE]
			(
				[ECO_LAN_OBJ_ID],
				[ECO_LAN_MODULE_ID],
				[ECO_LAN_LAN_ID],		
				[ECO_LAN_NAME]	
			)
			VALUES
			(
				@P_FEATURE_ID,
				@P_MODULE_ID,
				@P_ECO_LAN_LAN_ID,
				@P_FEATURE_NAME
			)
		
		IF @@ERROR != 0
            BEGIN 
                  ROLLBACK TRANSACTION
                  RETURN
            END

			COMMIT TRANSACTION @Transaction	
END
