CREATE PROCEDURE [ECOMMERCE].[FeatureAddOtherLang]
	@P_FEATURE_ID INT,
	@P_FEATURE_NAME NVARCHAR(500),
	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
    
AS
BEGIN
	SET NOCOUNT ON;
	
		INSERT INTO [ECOMMERCE].[ECOMMERCE_LANGUAGE]
			(
				[ECO_LAN_OBJ_ID],
				[ECO_LAN_MODULE_ID],
				[ECO_LAN_LAN_ID],		
				[ECO_LAN_NAME]	
			)
			VALUES
			(
				@P_FEATURE_ID,
				@P_MODULE_ID,
				@P_ECO_LAN_LAN_ID,
				@P_FEATURE_NAME
			)
			
END
