CREATE PROCEDURE [ECOMMERCE].[FeatureGetByProductID]
	@P_PRODUCT_ID INT,
	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
AS
BEGIN
	SET NOCOUNT ON;
	SELECT
			F.[FEATURE_ID],
			EL.[ECO_LAN_NAME],
			PF.[PRODUCT_FEATURE_VALUE]
			
	 FROM  [ECOMMERCE].[FEATURE] AS F
	   	    INNER JOIN
	   	   [ECOMMERCE].[PRODUCT_FEATURE] AS PF
	 ON			PF.PRODUCT_FEATURE_ID = F.FEATURE_ID
			AND
			    PF.PRODUCT_PRODUCT_ID  = @P_PRODUCT_ID
			LEFT OUTER JOIN
		   ECOMMERCE.ECOMMERCE_LANGUAGE AS EL
	 ON	
				EL.[ECO_LAN_OBJ_ID] = F.[FEATURE_ID]
			AND
				EL.[ECO_LAN_MODULE_ID] = @P_MODULE_ID
			AND
				EL.[ECO_LAN_LAN_ID] = @P_ECO_LAN_LAN_ID
		where
				F.[FEATURE_IS_DELETED] = 0
	END
