CREATE PROCEDURE [ECOMMERCE].[GroupAddOtherLang]
	@P_GROUP_ID INT,
	
	@P_GROUP_NAME NVARCHAR(500),
	@P_GROUP_PUBLIC_NAME NVARCHAR(500),
	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
    
AS
BEGIN
	SET NOCOUNT ON;
	
		INSERT INTO [ECOMMERCE].[ECOMMERCE_LANGUAGE]
			(
				[ECO_LAN_OBJ_ID],
				[ECO_LAN_MODULE_ID],
				[ECO_LAN_LAN_ID],		
				[ECO_LAN_NAME],
				[ECO_LAN_NAME2]	
			)
			VALUES
			(
				@P_GROUP_ID,
				@P_MODULE_ID,
				@P_ECO_LAN_LAN_ID,
				@P_GROUP_NAME,
				@P_GROUP_PUBLIC_NAME
			)
			
END
