CREATE PROCEDURE [ECOMMERCE].[GroupUpdate]
	@P_GROUP_ID INT,
	@P_GROUP_IS_COLOR_GROUP bit,
	@P_GROUP_PORTAL_ID INT,
	
	@P_GROUP_NAME NVARCHAR(500),
	@P_GROUP_PUBLIC_NAME NVARCHAR(500),
	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
    
AS
BEGIN
	SET NOCOUNT ON;
	
	DECLARE @Transaction VARCHAR(100);
	SELECT @Transaction = 'Transaction';

	BEGIN TRANSACTION @Transaction;
	
	update [ECOMMERCE].[GROUP]
		set 
		[GROUP_IS_COLOR_GROUP] = @P_GROUP_IS_COLOR_GROUP,
		GROUP_PORTAL_ID = @P_GROUP_PORTAL_ID
	
	where
		[GROUP_ID] = @P_GROUP_ID
		
	UPDATE [ECOMMERCE].[ECOMMERCE_LANGUAGE]
			SET 
			    [ECO_LAN_NAME] = @P_GROUP_NAME,
			    [ECO_LAN_NAME2] = @P_GROUP_PUBLIC_NAME
					WHERE 
				[ECO_LAN_OBJ_ID] = @P_GROUP_ID
			AND
				[ECO_LAN_MODULE_ID] = @P_MODULE_ID
			AND
				[ECO_LAN_LAN_ID] = @P_ECO_LAN_LAN_ID
	
	IF @@ERROR != 0
            BEGIN 
                  ROLLBACK TRANSACTION
                  RETURN
            END

			COMMIT TRANSACTION @Transaction			
END
