CREATE PROCEDURE [ECOMMERCE].[GroupAdd]
	@P_GROUP_ID INT OUTPUT,
	@P_GROUP_IS_COLOR_GROUP bit,
	@P_GROUP_PORTAL_ID INT,
	
	@P_GROUP_NAME NVARCHAR(500),
	@P_GROUP_PUBLIC_NAME NVARCHAR(500),
	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
    
AS
BEGIN
	SET NOCOUNT ON;
	
	DECLARE @Transaction VARCHAR(100);
	SELECT @Transaction = 'Transaction';

	BEGIN TRANSACTION @Transaction;
	
	INSERT INTO [ECOMMERCE].[GROUP]
		(
		[GROUP_IS_COLOR_GROUP],
		[GROUP_PORTAL_ID]
		)
	VALUES
		(
		    @P_GROUP_IS_COLOR_GROUP,
			@P_GROUP_PORTAL_ID
		)
		
		set @P_GROUP_ID=SCOPE_IDENTITY()
		
		INSERT INTO [ECOMMERCE].[ECOMMERCE_LANGUAGE]
			(
				[ECO_LAN_OBJ_ID],
				[ECO_LAN_MODULE_ID],
				[ECO_LAN_LAN_ID],		
				[ECO_LAN_NAME],
				[ECO_LAN_NAME2]	
			)
			VALUES
			(
				@P_GROUP_ID,
				@P_MODULE_ID,
				@P_ECO_LAN_LAN_ID,
				@P_GROUP_NAME,
				@P_GROUP_PUBLIC_NAME
			)
		IF @@ERROR != 0
            BEGIN 
                  ROLLBACK TRANSACTION
                  RETURN
            END

			COMMIT TRANSACTION @Transaction	
END
