CREATE PROCEDURE [ECOMMERCE].[ManufacturareAdd]

	@P_MANUFACTURARE_ID	int OUTPUT	,
	@P_MANUFACTURARE_LOGO_IMAGE nvarchar(500)	,
	@P_MANUFACTURARE_IS_ENABLED	bit,	
	@P_MANUFACTURARE_PORTAL_ID	int	,
	
	@P_MANUFACTURARE_DESCRIPTION NVARCHAR(500),
	@P_MANUFACTURARE_SHORT_DESCRIPTION NVARCHAR(500),
	@P_MANUFACTURARE_META_TITLE NVARCHAR(500),
	@P_MANUFACTURARE_META_DESCRIPTION NVARCHAR(500),
	@P_MANUFACTURARE_META_KEYWORDS NVARCHAR(500),

	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
    
AS
BEGIN
	SET NOCOUNT ON;
	
	DECLARE @Transaction VARCHAR(100);
	SELECT @Transaction = 'Transaction';

	BEGIN TRANSACTION @Transaction;

	INSERT INTO [ECOMMERCE].[MANUFACTURARE]
		(
		[MANUFACTURARE_LOGO_IMAGE],
		[MANUFACTURARE_IS_ENABLED],	
		[MANUFACTURARE_PORTAL_ID]
		)
	VALUES
		(
		@P_MANUFACTURARE_LOGO_IMAGE,
		@P_MANUFACTURARE_IS_ENABLED	,	
		@P_MANUFACTURARE_PORTAL_ID
		)
		
		set @P_MANUFACTURARE_ID=SCOPE_IDENTITY()
		
		INSERT INTO [ECOMMERCE].[ECOMMERCE_LANGUAGE]
			(
				[ECO_LAN_OBJ_ID],
				[ECO_LAN_MODULE_ID],
				[ECO_LAN_LAN_ID],
				
				[ECO_LAN_DESC],
				[ECO_LAN_DESC2],
				
				[ECO_LAN_NAME2],
				[ECO_LAN_DETAILS],
				[ECO_LAN_KEYWORD]			
			)
			VALUES
			(
				@P_MANUFACTURARE_ID,
				@P_MODULE_ID,
				@P_ECO_LAN_LAN_ID,
				
				@P_MANUFACTURARE_DESCRIPTION ,
				@P_MANUFACTURARE_SHORT_DESCRIPTION ,
				
				@P_MANUFACTURARE_META_TITLE ,
				@P_MANUFACTURARE_META_DESCRIPTION,
				@P_MANUFACTURARE_META_KEYWORDS
				
			)
			
			IF @@ERROR != 0
            BEGIN 
                  ROLLBACK TRANSACTION
                  RETURN
            END

			COMMIT TRANSACTION @Transaction

			
END
