CREATE PROCEDURE [ECOMMERCE].[ManufacturareGetAll]
	@P_MANUFACTURARE_PORTAL_ID int,
	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
AS
BEGIN
	SET NOCOUNT ON;
	SELECT
			M.[MANUFACTURARE_ID],
			M.[MANUFACTURARE_LOGO_IMAGE],
			M.[MANUFACTURARE_IS_ENABLED],
			M.[MANUFACTURARE_IS_DELETED],
			M.[MANUFACTURARE_PORTAL_ID],
			
			EL.[ECO_LAN_DESC],
			EL.[ECO_LAN_DESC2],	
			EL.[ECO_LAN_NAME2],
			EL.[ECO_LAN_DETAILS],
			EL.[ECO_LAN_KEYWORD],
			EL.[ECO_LAN_LAN_ID],	
			EL.[ECO_LAN_NAME],
			EL.[ECO_LAN_OBJ_ID]
	 FROM  [ECOMMERCE].[MANUFACTURARE] AS M
			LEFT OUTER JOIN
		   ECOMMERCE.ECOMMERCE_LANGUAGE AS EL
	 ON	
				EL.[ECO_LAN_OBJ_ID] = M.[MANUFACTURARE_ID]
			AND
				EL.[ECO_LAN_MODULE_ID] = @P_MODULE_ID
			AND
				EL.[ECO_LAN_LAN_ID] = @P_ECO_LAN_LAN_ID
		WHERE M.[MANUFACTURARE_IS_DELETED]=0 and [MANUFACTURARE_PORTAL_ID] = @P_MANUFACTURARE_PORTAL_ID
	END
