CREATE PROCEDURE [ECOMMERCE].[ManufacturareUpdate]

	@P_MANUFACTURARE_ID	int,
	@P_MANUFACTURARE_LOGO_IMAGE nvarchar(500)	,
	@P_MANUFACTURARE_IS_ENABLED	bit,	
	@P_MANUFACTURARE_PORTAL_ID	int	,
	
	@P_MANUFACTURARE_DESCRIPTION NVARCHAR(500),
	@P_MANUFACTURARE_SHORT_DESCRIPTION NVARCHAR(500),
	@P_MANUFACTURARE_META_TITLE NVARCHAR(500),
	@P_MANUFACTURARE_META_DESCRIPTION NVARCHAR(500),
	@P_MANUFACTURARE_META_KEYWORDS NVARCHAR(500),

	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
    
AS
BEGIN
	SET NOCOUNT ON;
	
	DECLARE @Transaction VARCHAR(100);
	SELECT @Transaction = 'Transaction';

	BEGIN TRANSACTION @Transaction;

	update [ECOMMERCE].[MANUFACTURARE]
		set
		[MANUFACTURARE_LOGO_IMAGE] = @P_MANUFACTURARE_LOGO_IMAGE,
		[MANUFACTURARE_IS_ENABLED] = @P_MANUFACTURARE_IS_ENABLED,	
		[MANUFACTURARE_PORTAL_ID] = @P_MANUFACTURARE_PORTAL_ID
		
		where 
		[MANUFACTURARE_ID] =  @P_MANUFACTURARE_ID
		
		update [ECOMMERCE].[ECOMMERCE_LANGUAGE]
			set
			
				[ECO_LAN_DESC] =  @P_MANUFACTURARE_DESCRIPTION,
				[ECO_LAN_DESC2] = @P_MANUFACTURARE_SHORT_DESCRIPTION,
				[ECO_LAN_NAME2] = @P_MANUFACTURARE_META_TITLE,
				[ECO_LAN_DETAILS] = @P_MANUFACTURARE_META_DESCRIPTION ,
				[ECO_LAN_KEYWORD] = @P_MANUFACTURARE_META_KEYWORDS			
				
			WHERE 
				[ECO_LAN_OBJ_ID] = @P_MANUFACTURARE_ID
			AND
				[ECO_LAN_MODULE_ID] = @P_MODULE_ID
			AND
				[ECO_LAN_LAN_ID] = @P_ECO_LAN_LAN_ID
				
			IF @@ERROR != 0
            BEGIN 
                  ROLLBACK TRANSACTION
                  RETURN
            END

			COMMIT TRANSACTION @Transaction

			
END
