CREATE PROCEDURE [ECOMMERCE].[ManufacturareAddOtherLang]

	@P_MANUFACTURARE_ID	int OUTPUT	,
	
	@P_MANUFACTURARE_DESCRIPTION NVARCHAR(500),
	@P_MANUFACTURARE_SHORT_DESCRIPTION NVARCHAR(500),
	@P_MANUFACTURARE_META_TITLE NVARCHAR(500),
	@P_MANUFACTURARE_META_DESCRIPTION NVARCHAR(500),
	@P_MANUFACTURARE_META_KEYWORDS NVARCHAR(500),

	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
    
AS
BEGIN
	SET NOCOUNT ON;

		INSERT INTO [ECOMMERCE].[ECOMMERCE_LANGUAGE]
			(
				[ECO_LAN_OBJ_ID],
				[ECO_LAN_MODULE_ID],
				[ECO_LAN_LAN_ID],
				
				[ECO_LAN_DESC],
				[ECO_LAN_DESC2],
				
				[ECO_LAN_NAME2],
				[ECO_LAN_DETAILS],
				[ECO_LAN_KEYWORD]			
			)
			VALUES
			(
				@P_MANUFACTURARE_ID,
				@P_MODULE_ID,
				@P_ECO_LAN_LAN_ID,
				
				@P_MANUFACTURARE_DESCRIPTION ,
				@P_MANUFACTURARE_SHORT_DESCRIPTION ,
				
				@P_MANUFACTURARE_META_TITLE ,
				@P_MANUFACTURARE_META_DESCRIPTION,
				@P_MANUFACTURARE_META_KEYWORDS
				
			)
			
END
