CREATE PROCEDURE [ECOMMERCE].[PreferenceUpdate]
	@P_PREFERENCE_ID INT,
	@P_PREFERENCE_IS_ENABLED bit
    
AS
BEGIN
	SET NOCOUNT ON;

	update [ECOMMERCE].[PREFERENCE]
			set
			 PREFERENCE_IS_ENABLED = @P_PREFERENCE_IS_ENABLED
			where 
			 PREFERENCE_ID = @P_PREFERENCE_ID
			
END
