CREATE PROCEDURE [ECOMMERCE].[PreferenceAdd]
	@P_PREFERENCE_ID INT OUT,
	@P_PREFERENCE_NAME NVARCHAR(200),
	@P_PREFERENCE_PORTAL_ID INT,
	@P_PREFERENCE_IS_ENABLED BIT
    
AS
BEGIN
	SET NOCOUNT ON;
	
	

	INSERT INTO [ECOMMERCE].[PREFERENCE]
		(
			PREFERENCE_NAME,
			PREFERENCE_PORTAL_ID ,
			PREFERENCE_IS_ENABLED 
		)
	VALUES
		(
			@P_PREFERENCE_NAME,
			@P_PREFERENCE_PORTAL_ID,
			@P_PREFERENCE_IS_ENABLED
		)

			set @P_PREFERENCE_ID =  SCOPE_IDENTITY()
			
END
