CREATE PROCEDURE [ECOMMERCE].[PreferenceGetByName]
	@P_PREFERENCE_NAME nvarchar(200)
    
AS
BEGIN
	SET NOCOUNT ON;

		select
			 PREFERENCE_ID,
			 PREFERENCE_NAME,
			 PREFERENCE_PORTAL_ID,
			 PREFERENCE_IS_ENABLED
	
		from [ECOMMERCE].[PREFERENCE]
		
			where 
			 PREFERENCE_NAME = @P_PREFERENCE_NAME
			
END
