CREATE PROCEDURE [ECOMMERCE].[ProductAdd]
	
			@P_PRODUCT_ID	int	output,
			@P_PRODUCT_SUPPLIER_ID	int	,
			@P_PRODUCT_EAN13_OR_JAN	nvarchar(500),
			@P_PRODUCT_UPC	nvarchar(500),
			@P_PRODUCT_LOCATION	nvarchar(500),
			@P_PRODUCT_IS_DOWNLODABLE	bit	,
			@P_PRODUCT_DISPLAY_ON_SALE_ICON	bit	,
			@P_PRODUCT_INITIAL_STOCK	int	,
			@P_PRODUCT_MINIMUM_QUANTITY int	,
			@P_PRODUCT_ADDITIONAL_SHIPPING_COST decimal,
			@P_PRODUCT_MANUFACTURER_ID	int	,
			@P_PRODUCT_IS_ENABLED	bit	,
			@P_PRODUCT_PORTAL_ID	int	,
			@P_PRODUCT_TAX_ID	int	,
			
			@P_MODULE_ID INT,
			@P_ECO_LAN_LAN_ID INT,
			
			@P_PRODUCT_NAME NVARCHAR(500),
			@P_PRODUCT_DISPLAY_TEXT_IN_STOCK NVARCHAR(500),
			@P_PRODUCT_DISPLAY_TEXT_BACK_ORDER NVARCHAR(500),
			@P_PRODUCT_DESCRIPTION NVARCHAR(500),
			@P_PRODUCT_SHORT_DESCRIPTION NVARCHAR(500),
			@P_PRODUCT_SIZE_CHART NVARCHAR(500),
			@P_PRODUCT_TAGS NVARCHAR(500)
    
AS
BEGIN
	SET NOCOUNT ON;
	
	DECLARE @Transaction VARCHAR(100);
	SELECT @Transaction = 'Transaction';

	BEGIN TRANSACTION @Transaction;

	INSERT INTO [ECOMMERCE].[PRODUCT]
		(
			[PRODUCT_SUPPLIER_ID],		
			[PRODUCT_EAN13_OR_JAN],
			[PRODUCT_UPC],	
			[PRODUCT_LOCATION],
			[PRODUCT_IS_DOWNLODABLE],
			[PRODUCT_DISPLAY_ON_SALE_ICON],
			[PRODUCT_INITIAL_STOCK],
			[PRODUCT_MINIMUM_QUANTITY],
			[PRODUCT_ADDITIONAL_SHIPPING_COST],
			[PRODUCT_MANUFACTURER_ID],
			[PRODUCT_IS_ENABLED],
			[PRODUCT_PORTAL_ID],
			[PRODUCT_TAX_ID]
		)
	VALUES
		(
			case when @P_PRODUCT_SUPPLIER_ID >0 then @P_PRODUCT_SUPPLIER_ID else null end	,
			@P_PRODUCT_EAN13_OR_JAN	,
			@P_PRODUCT_UPC,
			@P_PRODUCT_LOCATION,
			@P_PRODUCT_IS_DOWNLODABLE,
			@P_PRODUCT_DISPLAY_ON_SALE_ICON,
			@P_PRODUCT_INITIAL_STOCK,
			@P_PRODUCT_MINIMUM_QUANTITY,
			@P_PRODUCT_ADDITIONAL_SHIPPING_COST,
			case when  @P_PRODUCT_MANUFACTURER_ID > 0 then @P_PRODUCT_MANUFACTURER_ID else null end,
			@P_PRODUCT_IS_ENABLED,
			@P_PRODUCT_PORTAL_ID,
			case when @P_PRODUCT_TAX_ID	 >0 then @P_PRODUCT_TAX_ID else null end
		)
		
		set @P_PRODUCT_ID = SCOPE_IDENTITY()
		
		INSERT INTO [ECOMMERCE].[ECOMMERCE_LANGUAGE]
			(
				[ECO_LAN_OBJ_ID],
				[ECO_LAN_MODULE_ID],
				[ECO_LAN_LAN_ID],
						
				[ECO_LAN_NAME],	
				[ECO_LAN_MESSAGE1],
				[ECO_LAN_MESSAGE2],
				[ECO_LAN_DESC],
				[ECO_LAN_DESC2],
				[ECO_LAN_DETAILS],
				[ECO_LAN_KEYWORD]
			)
			VALUES
			(
				@P_PRODUCT_ID,
				@P_MODULE_ID,
				@P_ECO_LAN_LAN_ID,
				
				@P_PRODUCT_NAME,
				@P_PRODUCT_DISPLAY_TEXT_IN_STOCK ,
				@P_PRODUCT_DISPLAY_TEXT_BACK_ORDER,
				@P_PRODUCT_DESCRIPTION,
				@P_PRODUCT_SHORT_DESCRIPTION,
				@P_PRODUCT_SIZE_CHART,
				@P_PRODUCT_TAGS 
			)
			
			IF @@ERROR != 0
            BEGIN 
                  ROLLBACK TRANSACTION
                  RETURN
            END

			COMMIT TRANSACTION @Transaction

			
END
