CREATE PROCEDURE [ECOMMERCE].[ProductGetAll]
			@P_PRODUCT_PORTAL_ID int,
			@P_MODULE_ID INT,
			@P_ECO_LAN_LAN_ID INT
	
	AS
	BEGIN
		SET NOCOUNT ON;
		select
				P.[PRODUCT_ID],
				P.[PRODUCT_SUPPLIER_ID],
				P.[PRODUCT_EAN13_OR_JAN],
				P.[PRODUCT_UPC] ,
				P.[PRODUCT_LOCATION],
				P.[PRODUCT_IS_DOWNLODABLE],
				P.[PRODUCT_DISPLAY_ON_SALE_ICON],
				P.[PRODUCT_INITIAL_STOCK],
				P.[PRODUCT_MINIMUM_QUANTITY],
				P.[PRODUCT_ADDITIONAL_SHIPPING_COST],
				P.[PRODUCT_MANUFACTURER_ID] ,
				P.[PRODUCT_IS_ENABLED] ,
				P.[PRODUCT_IS_DELETED] ,
				P.[PRODUCT_PORTAL_ID] ,
				P.[PRODUCT_TAX_ID],

				
				EL.[ECO_LAN_LAN_ID],
				EL.[ECO_LAN_NAME],      
				EL.[ECO_LAN_MESSAGE1],  
				EL.[ECO_LAN_MESSAGE2],  
				EL.[ECO_LAN_DESC],      
				EL.[ECO_LAN_DESC2],     
				EL.[ECO_LAN_DETAILS],   
				EL.[ECO_LAN_KEYWORD]
		
	from 
		[ECOMMERCE].[PRODUCT] AS P
			LEFT OUTER JOIN
		[ECOMMERCE].[ECOMMERCE_LANGUAGE] AS EL
			ON	
				EL.[ECO_LAN_OBJ_ID] = P.[PRODUCT_ID]
			AND
				EL.[ECO_LAN_MODULE_ID] = @P_MODULE_ID
			AND
				EL.[ECO_LAN_LAN_ID] = @P_ECO_LAN_LAN_ID
		where
				P.[PRODUCT_IS_DELETED] = 0 and P.[PRODUCT_PORTAL_ID] =  @P_PRODUCT_PORTAL_ID
				
			

			
END
