CREATE PROCEDURE [ECOMMERCE].[ProductUpdate]
	
			@P_PRODUCT_ID	int,
			@P_PRODUCT_SUPPLIER_ID	int	,
			@P_PRODUCT_EAN13_OR_JAN	nvarchar(500),
			@P_PRODUCT_UPC	nvarchar(500),
			@P_PRODUCT_LOCATION	nvarchar(500),
			@P_PRODUCT_IS_DOWNLODABLE	bit	,
			@P_PRODUCT_DISPLAY_ON_SALE_ICON	bit	,
			@P_PRODUCT_INITIAL_STOCK	int	,
			@P_PRODUCT_MINIMUM_QUANTITY int	,
			@P_PRODUCT_ADDITIONAL_SHIPPING_COST decimal,
			@P_PRODUCT_MANUFACTURER_ID	int	,
			@P_PRODUCT_IS_ENABLED	bit	,
			@P_PRODUCT_PORTAL_ID	int	,
			@P_PRODUCT_TAX_ID	int	,
			
			@P_MODULE_ID INT,
			@P_ECO_LAN_LAN_ID INT,
			
			@P_PRODUCT_NAME NVARCHAR(500),
			@P_PRODUCT_DISPLAY_TEXT_IN_STOCK NVARCHAR(500),
			@P_PRODUCT_DISPLAY_TEXT_BACK_ORDER NVARCHAR(500),
			@P_PRODUCT_DESCRIPTION NVARCHAR(500),
			@P_PRODUCT_SHORT_DESCRIPTION NVARCHAR(500),
			@P_PRODUCT_SIZE_CHART NVARCHAR(500),
			@P_PRODUCT_TAGS NVARCHAR(500)
    
AS
BEGIN
	SET NOCOUNT ON;
	
	DECLARE @Transaction VARCHAR(100);
	SELECT @Transaction = 'Transaction';

	BEGIN TRANSACTION @Transaction;

	update [ECOMMERCE].[PRODUCT]
		set
			[PRODUCT_SUPPLIER_ID] = case when @P_PRODUCT_SUPPLIER_ID >0  then @P_PRODUCT_SUPPLIER_ID else null end,		
			[PRODUCT_EAN13_OR_JAN] = @P_PRODUCT_EAN13_OR_JAN,
			[PRODUCT_UPC] = @P_PRODUCT_UPC,	
			[PRODUCT_LOCATION]= @P_PRODUCT_LOCATION,
			[PRODUCT_IS_DOWNLODABLE] = @P_PRODUCT_IS_DOWNLODABLE,
			[PRODUCT_DISPLAY_ON_SALE_ICON] = @P_PRODUCT_DISPLAY_ON_SALE_ICON,
			[PRODUCT_INITIAL_STOCK] = @P_PRODUCT_INITIAL_STOCK,
			[PRODUCT_MINIMUM_QUANTITY] = @P_PRODUCT_MINIMUM_QUANTITY,
			[PRODUCT_ADDITIONAL_SHIPPING_COST] = @P_PRODUCT_ADDITIONAL_SHIPPING_COST,
			[PRODUCT_MANUFACTURER_ID] =case when  @P_PRODUCT_MANUFACTURER_ID >0 then [PRODUCT_MANUFACTURER_ID] else null end,
			[PRODUCT_IS_ENABLED] =@P_PRODUCT_IS_ENABLED,
			[PRODUCT_PORTAL_ID] =@P_PRODUCT_PORTAL_ID,
			[PRODUCT_TAX_ID] = case when @P_PRODUCT_TAX_ID	 >0 then @P_PRODUCT_TAX_ID else null end
		
		where [PRODUCT_ID] =@P_PRODUCT_ID
		 
		update [ECOMMERCE].[ECOMMERCE_LANGUAGE]
			set
					
				[ECO_LAN_NAME] = @P_PRODUCT_NAME,	
				[ECO_LAN_MESSAGE1]= @P_PRODUCT_DISPLAY_TEXT_IN_STOCK,
				[ECO_LAN_MESSAGE2] = @P_PRODUCT_DISPLAY_TEXT_BACK_ORDER,
				[ECO_LAN_DESC] = @P_PRODUCT_DESCRIPTION,
				[ECO_LAN_DESC2] = @P_PRODUCT_SHORT_DESCRIPTION,
				[ECO_LAN_DETAILS] = @P_PRODUCT_SIZE_CHART,
				[ECO_LAN_KEYWORD] = @P_PRODUCT_TAGS
			
			WHERE 
				[ECO_LAN_OBJ_ID] = @P_PRODUCT_ID
			AND
				[ECO_LAN_MODULE_ID] = @P_MODULE_ID
			AND
				[ECO_LAN_LAN_ID] = @P_ECO_LAN_LAN_ID
				
			IF @@ERROR != 0
            BEGIN 
                  ROLLBACK TRANSACTION
                  RETURN
            END

			COMMIT TRANSACTION @Transaction

			
END
