CREATE PROCEDURE [ECOMMERCE].[ProductAddOtherLang]
	
			@P_PRODUCT_ID int,
		
			@P_MODULE_ID INT,
			@P_ECO_LAN_LAN_ID INT,
			
			@P_PRODUCT_NAME NVARCHAR(500),
			@P_PRODUCT_DISPLAY_TEXT_IN_STOCK NVARCHAR(500),
			@P_PRODUCT_DISPLAY_TEXT_BACK_ORDER NVARCHAR(500),
			@P_PRODUCT_DESCRIPTION NVARCHAR(500),
			@P_PRODUCT_SHORT_DESCRIPTION NVARCHAR(500),
			@P_PRODUCT_SIZE_CHART NVARCHAR(500),
			@P_PRODUCT_TAGS NVARCHAR(500)
    
AS
BEGIN
	SET NOCOUNT ON;
	
		INSERT INTO [ECOMMERCE].[ECOMMERCE_LANGUAGE]
			(
				[ECO_LAN_OBJ_ID],
				[ECO_LAN_MODULE_ID],
				[ECO_LAN_LAN_ID],
						
				[ECO_LAN_NAME],	
				[ECO_LAN_MESSAGE1],
				[ECO_LAN_MESSAGE2],
				[ECO_LAN_DESC],
				[ECO_LAN_DESC2],
				[ECO_LAN_DETAILS],
				[ECO_LAN_KEYWORD]
			)
			VALUES
			(
				@P_PRODUCT_ID,
				@P_MODULE_ID,
				@P_ECO_LAN_LAN_ID,
				
				@P_PRODUCT_NAME,
				@P_PRODUCT_DISPLAY_TEXT_IN_STOCK ,
				@P_PRODUCT_DISPLAY_TEXT_BACK_ORDER,
				@P_PRODUCT_DESCRIPTION,
				@P_PRODUCT_SHORT_DESCRIPTION,
				@P_PRODUCT_SIZE_CHART,
				@P_PRODUCT_TAGS 
			)
		
			
END
