CREATE PROCEDURE [ECOMMERCE].[ProductPriceUpdate]

		@P_PRODUCT_PRICE_ID	int	,
		@P_PRODUCT_PRICE_CURRENCY_ID	int	,
		@P_PRODUCT_PRICE_COUNTRY_ID	int	,
		@P_PRODUCT_PRICE_FROM_DAY	int	,
		@P_PRODUCT_PRICE_FROM_SEC	int	,
		@P_PRODUCT_PRICE_TO_DAY	int	,
		@P_PRODUCT_PRICE_TO_SEC	int	,
		@P_PRODUCT_PRICE_START_AT	int	,
		@P_PRODUCT_PRICE_VALUE	decimal,
		@P_PRODUCT_PRICE_DISCOUNT_VALUE decimal	,
		@P_PRODUCT_PRICE_DISCOUNT_TYPE	int,
		@P_PRODUCT_PRICE_PRODUCT_ID int
    
AS
BEGIN
	SET NOCOUNT ON;
	
	update[ECOMMERCE].[PRODUCT_PRICE]
		set
		[PRODUCT_PRICE_CURRENCY_ID]	= @P_PRODUCT_PRICE_CURRENCY_ID	,
		[PRODUCT_PRICE_COUNTRY_ID]	= @P_PRODUCT_PRICE_COUNTRY_ID	,
		[PRODUCT_PRICE_FROM_DAY]= @P_PRODUCT_PRICE_FROM_DAY	,
		[PRODUCT_PRICE_FROM_SEC] = @P_PRODUCT_PRICE_FROM_SEC		,
		[PRODUCT_PRICE_TO_DAY]= @P_PRODUCT_PRICE_TO_DAY		,
		[PRODUCT_PRICE_TO_SEC]	= @P_PRODUCT_PRICE_TO_SEC	,
		[PRODUCT_PRICE_START_AT] =@P_PRODUCT_PRICE_START_AT		,
		[PRODUCT_PRICE_VALUE] = @P_PRODUCT_PRICE_VALUE	,
		[PRODUCT_PRICE_DISCOUNT_VALUE] = @P_PRODUCT_PRICE_DISCOUNT_VALUE 	,
		[PRODUCT_PRICE_DISCOUNT_TYPE] = @P_PRODUCT_PRICE_DISCOUNT_TYPE	,
		[PRODUCT_PRICE_PRODUCT_ID] = @P_PRODUCT_PRICE_PRODUCT_ID
	where 
	    [PRODUCT_PRICE_ID] =  @P_PRODUCT_PRICE_ID
		
END
