CREATE PROCEDURE [ECOMMERCE].[ProductImageGetAll]
	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
AS
BEGIN
	SET NOCOUNT ON;
	SELECT
			PRI.[PROD_IMAGE_ID],
			PRI.[PROD_PRODUCT_ID],
			PRI.[PROD_IMAGE_NAME],
			PRI.[PROD_IMAGE_IS_COVER_IMAGE],
			PRI.[PROD_IMAGE_IS_DELETED],
			
			EL.[ECO_LAN_LAN_ID],
			EL.[ECO_LAN_NAME],
			EL.[ECO_LAN_OBJ_ID]
	 FROM  [ECOMMERCE].[PRODUCT_IMAGE] AS PRI
			LEFT OUTER JOIN
		   ECOMMERCE.ECOMMERCE_LANGUAGE AS EL
	 ON	
				EL.[ECO_LAN_OBJ_ID] = PRI.[PROD_IMAGE_ID]
			AND
				EL.[ECO_LAN_MODULE_ID] = @P_MODULE_ID
			AND
				EL.[ECO_LAN_LAN_ID] = @P_ECO_LAN_LAN_ID
				
		WHERE PRI.[PROD_IMAGE_IS_DELETED]=0
	END
