CREATE PROCEDURE [ECOMMERCE].[ProductFeatureUpdate]

		@P_PRODUCT_PRODUCT_ID	int,	
		@P_PRODUCT_FEATURE_ID	int	,
		@P_PRODUCT_FEATURE_VALUE int
    
AS
BEGIN
	SET NOCOUNT ON;
	
	update 
	  [ECOMMERCE].[PRODUCT_FEATURE]
		set
			[PRODUCT_FEATURE_VALUE] = @P_PRODUCT_FEATURE_VALUE 
		where 
			[PRODUCT_PRODUCT_ID] = @P_PRODUCT_PRODUCT_ID
			and
			[PRODUCT_FEATURE_ID] = @P_PRODUCT_FEATURE_ID
	
END
