CREATE PROCEDURE [ECOMMERCE].[ProductPriceGetAll]

AS
BEGIN
	SET NOCOUNT ON;
	select
		[PRODUCT_PRICE_ID] 
		[PRODUCT_PRICE_CURRENCY_ID],
		[PRODUCT_PRICE_COUNTRY_ID],
		[PRODUCT_PRICE_FROM_DAY],
		[PRODUCT_PRICE_FROM_SEC],
		[PRODUCT_PRICE_TO_DAY],
		[PRODUCT_PRICE_TO_SEC],
		[PRODUCT_PRICE_START_AT],
		[PRODUCT_PRICE_VALUE],
		[PRODUCT_PRICE_DISCOUNT_VALUE],
		[PRODUCT_PRICE_DISCOUNT_TYPE],
		[PRODUCT_PRICE_PRODUCT_ID],
		[PRODUCT_PRICE_IS_DELETED]
	
		from [ECOMMERCE].[PRODUCT_PRICE]
		
END
