CREATE PROCEDURE [ECOMMERCE].[ProductFeatureDelete]

		@P_PRODUCT_ID	int,	
		@P_FEATURE_ID	int	
    
AS
BEGIN
	SET NOCOUNT ON;
	
	delete from  [ECOMMERCE].[PRODUCT_FEATURE]
		where
			[PRODUCT_PRODUCT_ID]= @P_PRODUCT_ID	
			and	
			[PRODUCT_FEATURE_ID] = @P_FEATURE_ID
			
			
	
END
