CREATE PROCEDURE [ECOMMERCE].[ProductFeatureAdd]

		@P_PRODUCT_ID	int,	
		@P_FEATURE_ID	int	,
		@P_PRODUCT_FEATURE_VALUE int
    
AS
BEGIN
	SET NOCOUNT ON;
	
	insert into
	  [ECOMMERCE].[PRODUCT_FEATURE]
		(
			[PRODUCT_PRODUCT_ID],
			[PRODUCT_FEATURE_ID],
			[PRODUCT_FEATURE_VALUE]
		)
		values
		(
			@P_PRODUCT_ID,
			@P_FEATURE_ID,
			@P_PRODUCT_FEATURE_VALUE 
		)
			
	
END
