CREATE PROCEDURE [ECOMMERCE].[ProductImageGetByCombinationId]
	@P_COMBINATION_ID int,
	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
AS
BEGIN
	SET NOCOUNT ON;
	SELECT
			PRI.[PROD_IMAGE_ID],
			PRI.[PROD_PRODUCT_ID],
			PRI.[PROD_IMAGE_NAME],
			PRI.[PROD_IMAGE_IS_COVER_IMAGE],
			PRI.[PROD_IMAGE_IS_DELETED],
			
			EL.[ECO_LAN_LAN_ID],
			EL.[ECO_LAN_NAME],
			EL.[ECO_LAN_OBJ_ID]
			
	 FROM  [ECOMMERCE].[PRODUCT_IMAGE] AS PRI
			INNER JOIN
		   [ECOMMERCE].[COMBINATION_IMAGE] AS CI
	 ON    
		   CI.COMBINATION_ID = 	@P_COMBINATION_ID
		   AND
		   CI.COMBINATION_IMAGE_ID = PRI.[PROD_IMAGE_ID]
		   
			LEFT OUTER JOIN
		   ECOMMERCE.ECOMMERCE_LANGUAGE AS EL
	 ON	
				EL.[ECO_LAN_OBJ_ID] = PRI.[PROD_IMAGE_ID]
			AND
				EL.[ECO_LAN_MODULE_ID] = @P_MODULE_ID
			AND
				EL.[ECO_LAN_LAN_ID] = @P_ECO_LAN_LAN_ID
				
		WHERE PRI.[PROD_IMAGE_IS_DELETED] = 0 
	END
