CREATE PROCEDURE [ECOMMERCE].[SupplierGetById]

	@P_SUPPLIER_ID int,
	@P_SUPPLIER_PORTAL_ID int,
	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
AS
BEGIN
	SET NOCOUNT ON;
	SELECT
			S.[SUPPLIER_ID],
			S.[SUPPLIER_LOGO_IMAGE],
			S.[SUPPLIER_IS_ENABLED],
			S.[SUPPLIER_PARENT_OBJ_ID],
			S.[SUPPLIER_IS_DELETED],
			S.[SUPPLIER_PORTAL_ID],
			EL.[ECO_LAN_NAME2],
			EL.[ECO_LAN_DESC2],
			EL.[ECO_LAN_DESC],
			EL.[ECO_LAN_KEYWORD],
			EL.[ECO_LAN_LAN_ID],
			EL.[ECO_LAN_NAME],
			EL.[ECO_LAN_OBJ_ID]
	 FROM  [ECOMMERCE].[SUPPLIER] AS S
			LEFT OUTER JOIN
		   ECOMMERCE.ECOMMERCE_LANGUAGE AS EL
	 ON	
				EL.[ECO_LAN_OBJ_ID] = S.[SUPPLIER_ID]
			AND
				EL.[ECO_LAN_MODULE_ID] = @P_MODULE_ID
			AND
				EL.[ECO_LAN_LAN_ID] = @P_ECO_LAN_LAN_ID
				
		WHERE S.[SUPPLIER_ID]= @P_SUPPLIER_ID and S.[SUPPLIER_PORTAL_ID] = @P_SUPPLIER_PORTAL_ID
	END
