CREATE PROCEDURE [ECOMMERCE].[SupplierAdd]

	@P_SUPPLIER_ID	int OUTPUT	,
	@P_SUPPLIER_LOGO_IMAGE nvarchar(500),
	@P_SUPPLIER_IS_ENABLED	bit,
	@P_SUPPLIER_PARENT_OBJ_ID int,
	@P_SUPPLIER_PORTAL_ID	int	,
	
	@P_SUPPLIER_NAME NVARCHAR(500),
	@P_SUPPLIER_DESCRIPTION NVARCHAR(500),
	
	@P_SUPPLIER_META_TITLE NVARCHAR(500),
	@P_SUPPLIER_META_DESCRIPTION NVARCHAR(500),
	@P_SUPPLIER_META_KEYWORDS NVARCHAR(500),

	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
    
AS
BEGIN
	SET NOCOUNT ON;
	
	DECLARE @Transaction VARCHAR(100);
	SELECT @Transaction = 'Transaction';

	BEGIN TRANSACTION @Transaction;

	INSERT INTO [ECOMMERCE].[SUPPLIER]
		(
		[SUPPLIER_LOGO_IMAGE],
		[SUPPLIER_IS_ENABLED],
		[SUPPLIER_PARENT_OBJ_ID],
		[SUPPLIER_PORTAL_ID]
		)
	VALUES
		(
		@P_SUPPLIER_LOGO_IMAGE,
		@P_SUPPLIER_IS_ENABLED,	
		@P_SUPPLIER_PARENT_OBJ_ID,
		@P_SUPPLIER_PORTAL_ID
		)
		
		set @P_SUPPLIER_ID = SCOPE_IDENTITY()
		
		INSERT INTO [ECOMMERCE].[ECOMMERCE_LANGUAGE]
			(
				[ECO_LAN_OBJ_ID],
				[ECO_LAN_MODULE_ID],
				[ECO_LAN_LAN_ID],
				
				[ECO_LAN_NAME],
				[ECO_LAN_DESC],
				[ECO_LAN_NAME2],
				[ECO_LAN_DESC2],
				[ECO_LAN_KEYWORD]			
			)
			VALUES
			(
				@P_SUPPLIER_ID,
				@P_MODULE_ID,
				@P_ECO_LAN_LAN_ID,
				
				@P_SUPPLIER_NAMe ,
				@P_SUPPLIER_DESCRIPTION ,
				
				@P_SUPPLIER_META_TITLE ,
				@P_SUPPLIER_META_DESCRIPTION,
				@P_SUPPLIER_META_KEYWORDS
				
			)
			
			IF @@ERROR != 0
            BEGIN 
                  ROLLBACK TRANSACTION
                  RETURN
            END

			COMMIT TRANSACTION @Transaction

			
END
