CREATE PROCEDURE [ECOMMERCE].[SupplierAddOtherLang]

	@P_SUPPLIER_ID	int ,

	@P_SUPPLIER_NAME NVARCHAR(500),
	@P_SUPPLIER_DESCRIPTION NVARCHAR(500),
	
	@P_SUPPLIER_META_TITLE NVARCHAR(500),
	@P_SUPPLIER_META_DESCRIPTION NVARCHAR(500),
	@P_SUPPLIER_META_KEYWORDS NVARCHAR(500),

	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
    
AS
BEGIN
	SET NOCOUNT ON;
	
		INSERT INTO [ECOMMERCE].[ECOMMERCE_LANGUAGE]
			(
				[ECO_LAN_OBJ_ID],
				[ECO_LAN_MODULE_ID],
				[ECO_LAN_LAN_ID],
				
				[ECO_LAN_NAME],
				[ECO_LAN_DESC],
				[ECO_LAN_NAME2],
				[ECO_LAN_DETAILS],
				[ECO_LAN_KEYWORD]			
			)
			VALUES
			(
				@P_SUPPLIER_ID,
				@P_MODULE_ID,
				@P_ECO_LAN_LAN_ID,
				
				@P_SUPPLIER_NAMe ,
				@P_SUPPLIER_DESCRIPTION ,
				
				@P_SUPPLIER_META_TITLE ,
				@P_SUPPLIER_META_DESCRIPTION,
				@P_SUPPLIER_META_KEYWORDS
				
			)
			
END
