CREATE PROCEDURE [ECOMMERCE].[SupplierUpdate]

	@P_SUPPLIER_ID	int OUTPUT	,
	
	@P_SUPPLIER_LOGO_IMAGE nvarchar(500),
	@P_SUPPLIER_IS_ENABLED	bit,
	@P_SUPPLIER_PARENT_OBJ_ID int,
	@P_SUPPLIER_PORTAL_ID	int	,
	
	@P_SUPPLIER_NAME NVARCHAR(500),
	@P_SUPPLIER_DESCRIPTION NVARCHAR(500),
	
	@P_SUPPLIER_META_TITLE NVARCHAR(500),
	@P_SUPPLIER_META_DESCRIPTION NVARCHAR(500),
	@P_SUPPLIER_META_KEYWORDS NVARCHAR(500),

	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
    
AS
BEGIN
	SET NOCOUNT ON;
	
	DECLARE @Transaction VARCHAR(100);
	SELECT @Transaction = 'Transaction';

	BEGIN TRANSACTION @Transaction;

	update [ECOMMERCE].[SUPPLIER]
		set
		[SUPPLIER_LOGO_IMAGE] = @P_SUPPLIER_LOGO_IMAGE,
		[SUPPLIER_IS_ENABLED] = @P_SUPPLIER_IS_ENABLED,
		[SUPPLIER_PARENT_OBJ_ID] = @P_SUPPLIER_PARENT_OBJ_ID,
		[SUPPLIER_PORTAL_ID] = @P_SUPPLIER_PORTAL_ID
	
	where SUPPLIER_ID = @P_SUPPLIER_ID
		
		update  [ECOMMERCE].[ECOMMERCE_LANGUAGE]
		set 
				[ECO_LAN_NAME] = @P_SUPPLIER_NAME,
				[ECO_LAN_DESC] = @P_SUPPLIER_DESCRIPTION,
				[ECO_LAN_NAME2] = @P_SUPPLIER_META_TITLE,
				[ECO_LAN_DESC2] = @P_SUPPLIER_META_DESCRIPTION,
				[ECO_LAN_KEYWORD] = @P_SUPPLIER_META_KEYWORDS			
			
			where 
				[ECO_LAN_OBJ_ID] = @P_SUPPLIER_ID
			AND
				[ECO_LAN_MODULE_ID] = @P_MODULE_ID
			AND
				[ECO_LAN_LAN_ID] = @P_ECO_LAN_LAN_ID
			
			IF @@ERROR != 0
            BEGIN 
                  ROLLBACK TRANSACTION
                  RETURN
            END

			COMMIT TRANSACTION @Transaction

			
END
