CREATE TABLE [GALLERY].[GALLERY] (
    [GALLERY_ID]            INT             IDENTITY (1, 1) NOT NULL,
    [GALLERY_NAME]          NVARCHAR (500)  NOT NULL,
    [GALLERY_DESCRIPTION]   NVARCHAR (1000) NOT NULL,
    [GALLERY_SUMMARY]       NVARCHAR (1000) NOT NULL,
    [GALLERY_KEYWORDS]      NVARCHAR (1000) NOT NULL,
    [GALLERY_SEO_NAME]      NVARCHAR (1000) NOT NULL,
    [GALLERY_DETAILS]       NTEXT           NOT NULL,
    [GALLERY_URL]           NVARCHAR (1000) NOT NULL,
    [GALLERY_FILE]          NVARCHAR (500)  NOT NULL,
    [GALLERY_CATEGORY_ID]   INT             NOT NULL,
    [GALLERY_CREATION_DAY]  INT             NOT NULL,
    [GALLERY_CREATION_SEC]  INT             NOT NULL,
    [GALLERY_IS_DELETED]    BIT             NOT NULL,
    [GALLERY_PORTAL_ID]     INT             NOT NULL,
    [GALLERY_LANGUAGE_ID]   INT             NOT NULL,
    [GALLERY_TYPE]          INT             NOT NULL,
    [GALLERY_ITEM_TYPE]     INT             NOT NULL,
    [GALLERY_ORDER]         INT             NOT NULL,
    [GALLERY_CREATED_BY]    INT             NOT NULL,
    [GALLERY_PARENT_OBJ_ID] INT             NOT NULL
);

