CREATE PROCEDURE [ARTICLE].[ArticleDeleteLogical]
	@P_ARTICLE_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Update [ARTICLE].[ARTICLE] set
	[ARTICLE_IS_DELETED]=1
	Where
	ARTICLE_ID=@P_ARTICLE_ID
	or
	(
		ARTICLE_PARENT_OBJ_ID = @P_ARTICLE_ID
	)
END
