CREATE PROCEDURE [ARTICLE].[ArticleGetByCategoryXML]
	@P_ARTICLE_CATEGORY_ID int,
	@P_ROW_FROM int,
	@P_ROW_TO int,
	@P_TOTAL_COUNT int output,
	@P_PUBLISH_MODULE_ID int,
	@P_PUBLISH_TYPE_ID int,
	@P_ARTICLE_LANGUAGE_ID INT
	
AS
BEGIN
	SET NOCOUNT ON;
	
	Select @P_TOTAL_COUNT = Count(1) from
		[ARTICLE].[ARTICLE]
		INNER JOIN
		[SETUP].[PUBLISH]
		ON 
		   [PUBLISH_OBJECT_ID] = case when [ARTICLE_PARENT_OBJ_ID] > 0 then [ARTICLE_PARENT_OBJ_ID]
		   else [ARTICLE_ID] end 
			AND	
			[ARTICLE_PORTAL_ID] = [PUBLISH_PORTAL_ID]
			---AND
			--[ARTICLE_LANGUAGE_ID] = [PUBLISH_LANGUAGE_ID] 
			AND
			[PUBLISH_MODULE_ID] = @P_PUBLISH_MODULE_ID
			AND
			[PUBLISH_TYPE_ID] = @P_PUBLISH_TYPE_ID
		where
			[ARTICLE_CATEGORY_ID] = @P_ARTICLE_CATEGORY_ID
			AND
			[ARTICLE_LANGUAGE_ID] = @P_ARTICLE_LANGUAGE_ID
			AND
			[ARTICLE_IS_DELETED] = 0
			
	Select 
		[ARTICLE_ID],
		[ARTICLE_NAME],
		[ARTICLE_DESCRIPTION],
		[ARTICLE_KEYWORDS],
		[ARTICLE_SEO_NAME],
		[ARTICLE_URL],
		[ARTICLE_IMAGE],
		[ARTICLE_SUMMARY],
		[ARTICLE_CATEGORY_ID],
		[ARTICLE_CREATION_DAY],
		[ARTICLE_CREATION_SEC],
		[ARTICLE_IS_DELETED],
		[ARTICLE_PORTAL_ID],
		[ARTICLE_LANGUAGE_ID],
		[ARTICLE_TYPE],
		[ARTICLE_ORDER],
		[ARTICLE_CREATED_BY],
		[ARTICLE_PARENT_OBJ_ID],
		[ARTICLE_VIEW_COUNT],
		[PUBLISH_TYPE_ID]
	From
	(
		Select 
			[ARTICLE_ID],
			[ARTICLE_NAME],
			[ARTICLE_DESCRIPTION],
			[ARTICLE_KEYWORDS],
			[ARTICLE_SEO_NAME],
			[ARTICLE_URL],
			[ARTICLE_IMAGE],
			[ARTICLE_SUMMARY],
			[ARTICLE_CATEGORY_ID],
			[ARTICLE_CREATION_DAY],
			[ARTICLE_CREATION_SEC],
			[ARTICLE_IS_DELETED],
			[ARTICLE_PORTAL_ID],
			[ARTICLE_LANGUAGE_ID],
			[ARTICLE_TYPE],
			[ARTICLE_ORDER],
			[ARTICLE_CREATED_BY],
			[ARTICLE_PARENT_OBJ_ID] ,
			[ARTICLE_VIEW_COUNT],
			[PUBLISH_TYPE_ID],
			Row_Number() over(order by [ARTICLE_ORDER],[ARTICLE_CREATION_DAY] DESC,[ARTICLE_CREATION_SEC] DESC) As [RowNumber]
		from
		[ARTICLE].[ARTICLE] AS A
		INNER JOIN
		[SETUP].[PUBLISH] AS P
		ON 
			[PUBLISH_OBJECT_ID] = case when [ARTICLE_PARENT_OBJ_ID] > 0 then [ARTICLE_PARENT_OBJ_ID]
		   else [ARTICLE_ID] end 
			AND	
			A.[ARTICLE_PORTAL_ID] = P.[PUBLISH_PORTAL_ID]
			--AND
			--A.[ARTICLE_LANGUAGE_ID] = P.[PUBLISH_LANGUAGE_ID]
			AND
			P.[PUBLISH_MODULE_ID] = @P_PUBLISH_MODULE_ID
			AND
			p.[PUBLISH_TYPE_ID] = @P_PUBLISH_TYPE_ID
		where
			A.[ARTICLE_CATEGORY_ID] = @P_ARTICLE_CATEGORY_ID
			AND
		    A.[ARTICLE_LANGUAGE_ID] =@P_ARTICLE_LANGUAGE_ID
			and
			A.[ARTICLE_IS_DELETED] = 0
	) As Item
	Where [RowNumber] Between @P_ROW_FROM AND @P_ROW_TO
	
	For XML AUTO,TYPE,ROOT('Parent')
END
