CREATE PROCEDURE [ARTICLE].[ArticleDelete]
	@P_ARTICLE_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Delete from [ARTICLE].[ARTICLE] 
		Where ARTICLE_ID=@P_ARTICLE_ID
		or
		(
			ARTICLE_PARENT_OBJ_ID = @P_ARTICLE_ID
		)
END
