CREATE PROCEDURE [ARTICLE].[GetLikeArticleName]
	@P_ARTICLE_NAME NVARCHAR(200),
	@P_TOP_COUNT int
AS
BEGIN
	SELECT TOP (@P_TOP_COUNT)
		 ARTICLE_NAME,
		 ARTICLE_ID,
		 ARTICLE_DESCRIPTION 
	FROM
		 ARTICLE.ARTICLE 
	WHERE
	 ARTICLE_NAME LIKE CASE WHEN  @P_ARTICLE_NAME ='' THEN ARTICLE_NAME  ELSE '%'+@P_ARTICLE_NAME+'%'  END
	 
END
