ALTER TABLE [GALLERY].[GALLERY]
    ADD CONSTRAINT [PK_GALLERY] PRIMARY KEY CLUSTERED ([GALLERY_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

