IF OBJECT_ID(N'[ECOMMERCE].[GetAllCountries]') IS NOT NULL
	DROP PROCEDURE [ECOMMERCE].[GetAllCountries]

GO
create PROCEDURE [ECOMMERCE].[GetAllCountries]
	
AS
BEGIN
	
	SET NOCOUNT ON;
	select COUNTRY_ID,COUNTRY_NAME from [ECOMMERCE].[COUNTRY]
END
