IF OBJECT_ID(N'[ECOMMERCE].[ProductAttributeAdd]') IS NOT NULL
	DROP PROCEDURE [ECOMMERCE].[ProductAttributeAdd]
go
create PROCEDURE [ECOMMERCE].[ProductAttributeAdd]
		@p_PRODUCT_ATTRIBUTE_ID int output,
		@P_PRO_ATT_ATTRIBUTE_ID	int,	
		@P_PRO_ATT_PRODUCT_ID	int	,
		@P_PRO_ATT_DETAILS nvarchar(max)
    
AS
BEGIN
	SET NOCOUNT ON;
	
	insert into
	  [ECOMMERCE].[PRODUCT_ATTRIBUTE]
		(
			[PRO_ATT_ATTRIBUTE_ID],
			[PRO_ATT_PRODUCT_ID],
			[PRO_ATT_DETAILS]
		)
		values
		(
			@P_PRO_ATT_ATTRIBUTE_ID,
			@P_PRO_ATT_PRODUCT_ID,
			@P_PRO_ATT_DETAILS 
		)
			
	set @p_PRODUCT_ATTRIBUTE_ID=SCOPE_IDENTITY()
END

go

IF OBJECT_ID(N'[ECOMMERCE].[ProductAttributeDelete]') IS NOT NULL
	DROP PROCEDURE [ECOMMERCE].[ProductAttributeDelete]
go


create PROCEDURE [ECOMMERCE].[ProductAttributeDelete]

		@p_PRODUCT_ATTRIBUTE_ID	int
    
AS
BEGIN
	SET NOCOUNT ON;
	
	delete from  [ECOMMERCE].[PRODUCT_ATTRIBUTE]
		where
		PRODUCT_ATTRIBUTE_ID=@p_PRODUCT_ATTRIBUTE_ID
	
END

go

IF OBJECT_ID(N'[ECOMMERCE].[ProductAttributeUpdate]') IS NOT NULL
	DROP PROCEDURE [ECOMMERCE].[ProductAttributeUpdate]
go

create PROCEDURE [ECOMMERCE].[ProductAttributeUpdate]

		@P_PRODUCT_ATTRIBUTE_ID	int,	
		@P_PRO_ATT_DETAILS nvarchar(max)
    
AS
BEGIN
	SET NOCOUNT ON;
	
	update 
	  [ECOMMERCE].[PRODUCT_ATTRIBUTE]
		set
			[PRO_ATT_DETAILS] = @P_PRO_ATT_DETAILS 
		where 
			[PRODUCT_ATTRIBUTE_ID] = @P_PRODUCT_ATTRIBUTE_ID
	
END
go

IF OBJECT_ID(N'[ECOMMERCE].[AttributeGetByProductID]') IS NOT NULL
	DROP PROCEDURE [ECOMMERCE].[AttributeGetByProductID]
go
create PROCEDURE [ECOMMERCE].[AttributeGetByProductID]
	@P_PRO_ATT_PRODUCT_ID INT,
	@P_MODULE_ID INT,
	@P_ECO_LAN_LAN_ID INT
AS
BEGIN
	SET NOCOUNT ON;
	SELECT
			pa.PRODUCT_ATTRIBUTE_ID,
			a.ATTRIBUTE_ID,
			pa.PRO_ATT_DETAILS,
			EL.ECO_LAN_NAME,
			g.GROUP_ID,
			(select ECL.ECO_LAN_NAME from ECOMMERCE.ECOMMERCE_LANGUAGE as ECL where ecl.ECO_LAN_MODULE_ID=5 and ecl.ECO_LAN_OBJ_ID=g.GROUP_ID) AS GroupName
			
	 FROM  [ECOMMERCE].[ATTRIBUTE] AS a
	   	    INNER JOIN
	   	   [ECOMMERCE].[PRODUCT_ATTRIBUTE] AS pa
	 ON			pa.PRO_ATT_ATTRIBUTE_ID = a.ATTRIBUTE_ID
			AND
			    pa.PRO_ATT_PRODUCT_ID  = @P_PRO_ATT_PRODUCT_ID
			LEFT OUTER JOIN
		   ECOMMERCE.ECOMMERCE_LANGUAGE AS EL
	 ON	
				EL.[ECO_LAN_OBJ_ID] = a.ATTRIBUTE_ID
			AND
				EL.[ECO_LAN_MODULE_ID] = @P_MODULE_ID
			AND
				EL.[ECO_LAN_LAN_ID] = @P_ECO_LAN_LAN_ID
				left outer join 
				ECOMMERCE.[GROUP] as g
				on
				a.ATTRIBUTE_GROUP_ID = g.GROUP_ID
		where
				a.ATTRIBUTE_IS_DELETED = 0
	END
