--region Drop Existing Procedures

IF OBJECT_ID(N'[ECOMMERCE].[OrderProductDetailsAdd]') IS NOT NULL
	DROP PROCEDURE [ECOMMERCE].[OrderProductDetailsAdd]

IF OBJECT_ID(N'[ECOMMERCE].[OrderProductDetailsUpdate]') IS NOT NULL
	DROP PROCEDURE [ECOMMERCE].[OrderProductDetailsUpdate]

IF OBJECT_ID(N'[ECOMMERCE].[OrderProductDetailsDelete]') IS NOT NULL
	DROP PROCEDURE [ECOMMERCE].[OrderProductDetailsDelete]

IF OBJECT_ID(N'[ECOMMERCE].[OrderProductDetailsGetByID]') IS NOT NULL
	DROP PROCEDURE [ECOMMERCE].[OrderProductDetailsGetByID]

IF OBJECT_ID(N'[ECOMMERCE].[OrderProductDetailsGetAll]') IS NOT NULL
	DROP PROCEDURE [ECOMMERCE].[OrderProductDetailsGetAll]


IF OBJECT_ID(N'[ECOMMERCE].[OrderProductDetailsGetByDetailsID]') IS NOT NULL
	DROP PROCEDURE [ECOMMERCE].[OrderProductDetailsGetByDetailsID]

--endregion

GO

--region [ECOMMERCE].[OrderProductDetailsAdd]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Qasem Al-Hammouri

-- Procedure Name: [ECOMMERCE].[OrderProductDetailsAdd]
-- Date Generated: Tuesday, April 23, 2013
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [ECOMMERCE].[OrderProductDetailsAdd]
	@P_ORD_PRO_DET_PRODUCT_ID int,
	@P_ORD_PRO_DET_ATTRIBUTE_ID int,
	@P_ORD_PRO_DET_DETAILS_ID int,
	@P_ORD_PRO_DET_XREF_PRODUCT_DETAILS int,
	@P_ORD_PRO_DET_GROUP_ID int,
	@P_ORD_PRO_DET_ID int OUTPUT
AS

SET NOCOUNT ON

INSERT INTO [ECOMMERCE].[ORDER_PRODUCT_DETAILS] (
	[ORD_PRO_DET_PRODUCT_ID],
	[ORD_PRO_DET_ATTRIBUTE_ID],
	[ORD_PRO_DET_DETAILS_ID],
	[ORD_PRO_DET_XREF_PRODUCT_DETAILS],
	[ORD_PRO_DET_GROUP_ID]
) VALUES (
	@P_ORD_PRO_DET_PRODUCT_ID,
	@P_ORD_PRO_DET_ATTRIBUTE_ID,
	@P_ORD_PRO_DET_DETAILS_ID,
	@P_ORD_PRO_DET_XREF_PRODUCT_DETAILS,
	@P_ORD_PRO_DET_GROUP_ID
)

SET @P_ORD_PRO_DET_ID = SCOPE_IDENTITY()

--endregion

GO

--region [ECOMMERCE].[OrderProductDetailsUpdate]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Qasem Al-Hammouri

-- Procedure Name: [ECOMMERCE].[OrderProductDetailsUpdate]
-- Date Generated: Tuesday, April 23, 2013
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [ECOMMERCE].[OrderProductDetailsUpdate]
	@P_ORD_PRO_DET_ID int,
	@P_ORD_PRO_DET_PRODUCT_ID int,
	@P_ORD_PRO_DET_ATTRIBUTE_ID int,
	@P_ORD_PRO_DET_DETAILS_ID int,
	@P_ORD_PRO_DET_XREF_PRODUCT_DETAILS int,
	@P_ORD_PRO_DET_GROUP_ID int
AS

SET NOCOUNT ON

UPDATE [ECOMMERCE].[ORDER_PRODUCT_DETAILS] SET
	[ORD_PRO_DET_PRODUCT_ID] = @P_ORD_PRO_DET_PRODUCT_ID,
	[ORD_PRO_DET_ATTRIBUTE_ID] = @P_ORD_PRO_DET_ATTRIBUTE_ID,
	[ORD_PRO_DET_DETAILS_ID] = @P_ORD_PRO_DET_DETAILS_ID,
	[ORD_PRO_DET_XREF_PRODUCT_DETAILS] = @P_ORD_PRO_DET_XREF_PRODUCT_DETAILS,
	[ORD_PRO_DET_GROUP_ID]=@P_ORD_PRO_DET_GROUP_ID
WHERE
	[ORD_PRO_DET_ID] = @P_ORD_PRO_DET_ID

--endregion

GO

--region [ECOMMERCE].[OrderProductDetailsDelete]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Qasem Al-Hammouri

-- Procedure Name: [ECOMMERCE].[OrderProductDetailsDelete]
-- Date Generated: Tuesday, April 23, 2013
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [ECOMMERCE].[OrderProductDetailsDelete]
	@P_ORD_PRO_DET_ID int
AS

SET NOCOUNT ON

DELETE FROM [ECOMMERCE].[ORDER_PRODUCT_DETAILS]
WHERE
	[ORD_PRO_DET_ID] = @P_ORD_PRO_DET_ID

--endregion

GO

--region [ECOMMERCE].[OrderProductDetailsGetByID]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Qasem Al-Hammouri

-- Procedure Name: [ECOMMERCE].[OrderProductDetailsGetByID]
-- Date Generated: Tuesday, April 23, 2013
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [ECOMMERCE].[OrderProductDetailsGetByID]
	@P_ORD_PRO_DET_ID int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[ORD_PRO_DET_ID],
	[ORD_PRO_DET_PRODUCT_ID],
	[ORD_PRO_DET_ATTRIBUTE_ID],
	[ORD_PRO_DET_DETAILS_ID],
	[ORD_PRO_DET_XREF_PRODUCT_DETAILS],
	[ORD_PRO_DET_GROUP_ID]
FROM
	[ECOMMERCE].[ORDER_PRODUCT_DETAILS]
WHERE
	[ORD_PRO_DET_ID] = @P_ORD_PRO_DET_ID

--endregion

GO

--region [ECOMMERCE].[OrderProductDetailsGetAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Qasem Al-Hammouri

-- Procedure Name: [ECOMMERCE].[OrderProductDetailsGetAll]
-- Date Generated: Tuesday, April 23, 2013
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [ECOMMERCE].[OrderProductDetailsGetAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[ORD_PRO_DET_ID],
	[ORD_PRO_DET_PRODUCT_ID],
	[ORD_PRO_DET_ATTRIBUTE_ID],
	[ORD_PRO_DET_DETAILS_ID],
	[ORD_PRO_DET_XREF_PRODUCT_DETAILS],
	[ORD_PRO_DET_GROUP_ID]
FROM
	[ECOMMERCE].[ORDER_PRODUCT_DETAILS]

--endregion

GO


--region [ECOMMERCE].[OrderProductDetailsGetByID]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Qasem Al-Hammouri

-- Procedure Name: [ECOMMERCE].[OrderProductDetailsGetByID]
-- Date Generated: Tuesday, April 23, 2013
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [ECOMMERCE].[OrderProductDetailsGetByDetailsID]
	@P_ORD_PRO_DET_DETAILS_ID int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[ORD_PRO_DET_ID],
	[ORD_PRO_DET_PRODUCT_ID],
	[ORD_PRO_DET_ATTRIBUTE_ID],
	[ORD_PRO_DET_DETAILS_ID],
	[ORD_PRO_DET_XREF_PRODUCT_DETAILS],
	[ORD_PRO_DET_GROUP_ID]
FROM
	[ECOMMERCE].[ORDER_PRODUCT_DETAILS]
WHERE
	[ORD_PRO_DET_DETAILS_ID] = @P_ORD_PRO_DET_DETAILS_ID

--endregion

GO