ALTER TABLE [SETUP].[CMSCONTROL]
    ADD CONSTRAINT [PK_CMSCONTROL] PRIMARY KEY CLUSTERED ([CMSCONTROL_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

