ALTER TABLE [SETUP].[LANGUAGE_URL]
    ADD CONSTRAINT [PK_LANGUAGE_URL] PRIMARY KEY CLUSTERED ([LANGUAGE_URL_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

