ALTER TABLE [SETUP].[MENU]
    ADD CONSTRAINT [PK_MENU] PRIMARY KEY CLUSTERED ([MENU_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

