ALTER TABLE [SETUP].[MODULE]
    ADD CONSTRAINT [PK_MODULE] PRIMARY KEY CLUSTERED ([MODULE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

