ALTER TABLE [SETUP].[PUBLISH]
    ADD CONSTRAINT [PK_PUBLISH] PRIMARY KEY CLUSTERED ([PUBLISH_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

