ALTER TABLE [SETUP].[STYLE]
    ADD CONSTRAINT [PK_STYLE] PRIMARY KEY CLUSTERED ([STYLE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

