ALTER TABLE [SETUP].[TEMPLATE]
    ADD CONSTRAINT [PK_TEMPLATE] PRIMARY KEY CLUSTERED ([TEMPLATE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

