ALTER TABLE [SETUP].[XSLTEMPLATE]
    ADD CONSTRAINT [PK_XSLTEMPLATE] PRIMARY KEY CLUSTERED ([XSLTEMPLATE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

