ALTER TABLE [ECOMMERCE].[COMBINATION_IMAGE]
    ADD CONSTRAINT [FK_COMBINATION_IMAGE_PRODUCT_IMAGE] FOREIGN KEY ([COMBINATION_IMAGE_ID]) REFERENCES [ECOMMERCE].[PRODUCT_IMAGE] ([PROD_IMAGE_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

