ALTER TABLE [ECOMMERCE].[COMBINATION_IMAGE]
    ADD CONSTRAINT [FK_COMBINATION_IMAGE_PRODUCT_COMBINATION] FOREIGN KEY ([COMBINATION_ID]) REFERENCES [ECOMMERCE].[COMBINATION_PRODUCT] ([COMBINATION_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

