ALTER TABLE [ECOMMERCE].[COMBINATION_ATTRIBUTE]
    ADD CONSTRAINT [FK_COMBINATION_ATTRIBUTE_PRODUCT_COMBINATION] FOREIGN KEY ([COMBINATION_ID]) REFERENCES [ECOMMERCE].[COMBINATION_PRODUCT] ([COMBINATION_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

