ALTER TABLE [ECOMMERCE].[CATALOG]
    ADD CONSTRAINT [FK_CATALOG_CATALOG1] FOREIGN KEY ([CATALOG_PARENT_CATALOG_ID]) REFERENCES [ECOMMERCE].[CATALOG] ([CATALOG_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

