ALTER TABLE [ECOMMERCE].[COMBINATION_ATTRIBUTE]
    ADD CONSTRAINT [FK_COMBINATION_ATTRIBUTE_ATTRIBUTE] FOREIGN KEY ([ATTRIBUTE_ID]) REFERENCES [ECOMMERCE].[ATTRIBUTE] ([ATTRIBUTE_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

