ALTER TABLE [ECOMMERCE].[PRODUCT_PRICE]
    ADD CONSTRAINT [FK_PRODUCT_PRICE_PRODUCT] FOREIGN KEY ([PRODUCT_PRICE_TO_SEC]) REFERENCES [ECOMMERCE].[PRODUCT] ([PRODUCT_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

