ALTER TABLE [ECOMMERCE].[PRODUCT_FEATURE]
    ADD CONSTRAINT [FK_PRODUCT_FEATURE_FEATURE] FOREIGN KEY ([PRODUCT_FEATURE_ID]) REFERENCES [ECOMMERCE].[FEATURE] ([FEATURE_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

