ALTER TABLE [ECOMMERCE].[PRODUCT_CATALOG]
    ADD CONSTRAINT [FK_PRODUCT_CATALOG_CATALOG] FOREIGN KEY ([CATALOG_ID]) REFERENCES [ECOMMERCE].[CATALOG] ([CATALOG_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

