ALTER TABLE [ECOMMERCE].[PRODUCT]
    ADD CONSTRAINT [FK_PRODUCT_MANUFACTURARE] FOREIGN KEY ([PRODUCT_MANUFACTURER_ID]) REFERENCES [ECOMMERCE].[MANUFACTURARE] ([MANUFACTURARE_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

