ALTER TABLE [ECOMMERCE].[PRODUCT_FEATURE]
    ADD CONSTRAINT [FK_PRODUCT_FEATURE_PRODUCT] FOREIGN KEY ([PRODUCT_PRODUCT_ID]) REFERENCES [ECOMMERCE].[PRODUCT] ([PRODUCT_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

