ALTER TABLE [ECOMMERCE].[PRODUCT_IMAGE]
    ADD CONSTRAINT [FK_PRODUCT_IMAGE_PRODUCT] FOREIGN KEY ([PROD_PRODUCT_ID]) REFERENCES [ECOMMERCE].[PRODUCT] ([PRODUCT_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

