ALTER TABLE [ECOMMERCE].[COMBINATION_PRODUCT]
    ADD CONSTRAINT [FK_PRODUCT_COMBINATION_PRODUCT] FOREIGN KEY ([COMBINATION_PRODUCT_ID]) REFERENCES [ECOMMERCE].[PRODUCT] ([PRODUCT_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

