ALTER TABLE [ECOMMERCE].[PRODUCT]
    ADD CONSTRAINT [FK_PRODUCT_SUPPLIER] FOREIGN KEY ([PRODUCT_SUPPLIER_ID]) REFERENCES [ECOMMERCE].[SUPPLIER] ([SUPPLIER_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

