ALTER TABLE [ECOMMERCE].[PRODUCT_CATALOG]
    ADD CONSTRAINT [FK_PRODUCT_CATALOG_PRODUCT] FOREIGN KEY ([PRODUCT_ID]) REFERENCES [ECOMMERCE].[PRODUCT] ([PRODUCT_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

