ALTER TABLE [ECOMMERCE].[ATTRIBUTE]
    ADD CONSTRAINT [PK_ATTRIBUTE] PRIMARY KEY CLUSTERED ([ATTRIBUTE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

