ALTER TABLE [ECOMMERCE].[CATALOG]
    ADD CONSTRAINT [PK_CATALOG] PRIMARY KEY CLUSTERED ([CATALOG_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

