ALTER TABLE [ECOMMERCE].[COMBINATION_ATTRIBUTE]
    ADD CONSTRAINT [PK_COMBINATION_ATTRIBUTE] PRIMARY KEY CLUSTERED ([COMBINATION_ID] ASC, [ATTRIBUTE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

