ALTER TABLE [ECOMMERCE].[COMBINATION_IMAGE]
    ADD CONSTRAINT [PK_COMBINATION_IMAGE_1] PRIMARY KEY CLUSTERED ([COMBINATION_IMAGE_ID] ASC, [COMBINATION_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

