ALTER TABLE [ECOMMERCE].[ECOMMERCE_LANGUAGE]
    ADD CONSTRAINT [PK_ECOMMERCE_LANGUAGE] PRIMARY KEY CLUSTERED ([ECO_LAN_OBJ_ID] ASC, [ECO_LAN_MODULE_ID] ASC, [ECO_LAN_LAN_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

