ALTER TABLE [ECOMMERCE].[FEATURE]
    ADD CONSTRAINT [PK_FEATURE] PRIMARY KEY CLUSTERED ([FEATURE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

