ALTER TABLE [ECOMMERCE].[GROUP]
    ADD CONSTRAINT [PK_GROUP] PRIMARY KEY CLUSTERED ([GROUP_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

