ALTER TABLE [ECOMMERCE].[MANUFACTURARE]
    ADD CONSTRAINT [PK_MANUFACTURARE] PRIMARY KEY CLUSTERED ([MANUFACTURARE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

