ALTER TABLE [ECOMMERCE].[PRODUCT]
    ADD CONSTRAINT [PK_PRODUCT] PRIMARY KEY CLUSTERED ([PRODUCT_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

