ALTER TABLE [ECOMMERCE].[PRODUCT_IMAGE]
    ADD CONSTRAINT [PK_PRODUCT_IMAGE] PRIMARY KEY CLUSTERED ([PROD_IMAGE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

