ALTER TABLE [ECOMMERCE].[COMBINATION_PRODUCT]
    ADD CONSTRAINT [PK_PRODUCT_COMBINATION] PRIMARY KEY CLUSTERED ([COMBINATION_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

