ALTER TABLE [ECOMMERCE].[PRODUCT_FEATURE]
    ADD CONSTRAINT [PK_PRODUCT_FEATURE] PRIMARY KEY CLUSTERED ([PRODUCT_FEATURE_ID] ASC, [PRODUCT_PRODUCT_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

