CREATE TABLE [SECURITY].[FORM_USER] (
    [FORM_USER_ID]          INT IDENTITY (1, 1) NOT NULL,
    [FORM_USER_FORM_ID]     INT NOT NULL,
    [FORM_USER_USER_ID]     INT NOT NULL,
    [FORM_USER_ACCESS_TYPE] INT NOT NULL
);

