CREATE TABLE [SECURITY].[FORM_ROLE] (
    [FORM_ROLE_ID]          INT IDENTITY (1, 1) NOT NULL,
    [FORM_ROLE_FORM_ID]     INT NOT NULL,
    [FORM_ROLE_ROLE_ID]     INT NOT NULL,
    [FORM_ROLE_ACCESS_TYPE] INT NOT NULL
);

