CREATE TABLE [SECURITY].[USER] (
    [USER_ID]           INT             IDENTITY (1, 1) NOT NULL,
    [USER_NAME]         NVARCHAR (1000) NOT NULL,
    [USER_EMAIL]        NVARCHAR (1000) NOT NULL,
    [USER_PASSWORD]     NVARCHAR (MAX)  NOT NULL,
    [USER_IS_ACTIVE]    BIT             NOT NULL,
    [USER_CREATION_DAY] INT             NOT NULL,
    [USER_CREATION_SEC] INT             NOT NULL,
    [USER_IS_DELETED]   BIT             NOT NULL
);

