CREATE PROCEDURE [SECURITY].[FormRoleDeleteByFormRole]
	@P_FORM_ROLE_FORM_ID int,
	@P_FORM_ROLE_ROLE_ID int
AS
BEGIN
	SET NOCOUNT ON;
	DELETE FROM [SECURITY].[FORM_ROLE]
	where
		(@P_FORM_ROLE_FORM_ID = -1 or [FORM_ROLE_FORM_ID] = @P_FORM_ROLE_FORM_ID)
		and
		(@P_FORM_ROLE_ROLE_ID = -1 or [FORM_ROLE_ROLE_ID] = @P_FORM_ROLE_ROLE_ID)
END
