CREATE PROCEDURE [SECURITY].[FormUserGetByID]
	@P_FORM_USER_ID int
AS
BEGIN
	SET NOCOUNT ON;
	SELECT
		fu.[FORM_USER_ID]
		,fu.[FORM_USER_FORM_ID]
		,fu.[FORM_USER_USER_ID]
		,fu.[FORM_USER_ACCESS_TYPE]
		,f.[FORM_CODE]
		,u.[USER_NAME]
	FROM
	[SECURITY].[FORM_USER] fu
	INNER JOIN
	[SECURITY].[FORM] f
	on
	fu.FORM_USER_FORM_ID = f.[FORM_ID]
	INNER JOIN
	[SECURITY].[USER] u
	on
	fu.FORM_USER_USER_ID = u.[USER_ID]
	where
	fu.[FORM_USER_ID] = @P_FORM_USER_ID
	and
	f.FORM_IS_DELETED = 0
	and
	u.[USER_IS_DELETED] = 0
END
