CREATE PROCEDURE [SECURITY].[FormUserAdd]
	@P_FORM_USER_ID int output,
	@P_FORM_USER_FORM_ID int,
	@P_FORM_USER_USER_ID int,
	@P_FORM_USER_ACCESS_TYPE int
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [SECURITY].[FORM_USER]
		(
		[FORM_USER_FORM_ID]
		,[FORM_USER_USER_ID]
		,[FORM_USER_ACCESS_TYPE]
		)
	VALUES
		(
		@P_FORM_USER_FORM_ID
		,@P_FORM_USER_USER_ID
		,@P_FORM_USER_ACCESS_TYPE
		)
		
		set @P_FORM_USER_ID=SCOPE_IDENTITY()
END
