CREATE PROCEDURE [SECURITY].[FormUserUpdate]
	@P_FORM_USER_ID int,
	@P_FORM_USER_FORM_ID int,
	@P_FORM_USER_USER_ID int,
	@P_FORM_USER_ACCESS_TYPE int
AS
BEGIN
	SET NOCOUNT ON;
	UPDATE [SECURITY].[FORM_USER] SET
		[FORM_USER_FORM_ID] = @P_FORM_USER_FORM_ID
		,[FORM_USER_USER_ID] = @P_FORM_USER_USER_ID
		,[FORM_USER_ACCESS_TYPE] = @P_FORM_USER_ACCESS_TYPE
	where
		[FORM_USER_ID] = @P_FORM_USER_ID
END
