CREATE PROCEDURE [SECURITY].[FormRoleUpdate]
	@P_FORM_ROLE_ID int,
	@P_FORM_ROLE_FORM_ID int,
	@P_FORM_ROLE_ROLE_ID int,
	@P_FORM_ROLE_ACCESS_TYPE int
AS
BEGIN
	SET NOCOUNT ON;
	UPDATE [SECURITY].[FORM_ROLE] SET
		[FORM_ROLE_FORM_ID] = @P_FORM_ROLE_FORM_ID
		,[FORM_ROLE_ROLE_ID] = @P_FORM_ROLE_ROLE_ID
		,[FORM_ROLE_ACCESS_TYPE] = @P_FORM_ROLE_ACCESS_TYPE
	where
		[FORM_ROLE_ID] = @P_FORM_ROLE_ID
END
