CREATE PROCEDURE [SECURITY].[FormAdd]
	@P_FORM_ID int output,
	@P_FORM_NAME nvarchar(1024),
	@P_FORM_DESCRIPTION nvarchar(1024),
	@P_FORM_URL nvarchar(max),
	@P_FORM_CODE nvarchar(1024),
	@P_FORM_MODULE_ID int,
	@P_FORM_IS_DELETED bit
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [SECURITY].[FORM]
		(
		[FORM_NAME]
		,[FORM_DESCRIPTION]
		,[FORM_URL]
		,[FORM_CODE]
		,[FORM_MODULE_ID]
		,[FORM_IS_DELETED]
		)
	VALUES
		(
		@P_FORM_NAME
		,@P_FORM_DESCRIPTION
		,@P_FORM_URL
		,@P_FORM_CODE
		,@P_FORM_MODULE_ID
		,@P_FORM_IS_DELETED
		)
		
		set @P_FORM_ID=SCOPE_IDENTITY()
END
