CREATE PROCEDURE [SECURITY].[FormGetByID]
	@P_FORM_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Select 
		[FORM_ID]
		,[FORM_NAME]
		,[FORM_DESCRIPTION]
		,[FORM_URL]
		,[FORM_CODE]
		,[FORM_MODULE_ID]
		,[FORM_IS_DELETED]
 from [SECURITY].[FORM]
 where 
 [FORM_IS_DELETED] = 0
 And
 [FORM_ID] = @P_FORM_ID
END
