CREATE PROCEDURE [SECURITY].[FormGetByCode]
	@P_FORM_CODE nvarchar(1024)
AS
BEGIN
	SET NOCOUNT ON;
	Select 
		[FORM_ID]
		,[FORM_NAME]
		,[FORM_DESCRIPTION]
		,[FORM_URL]
		,[FORM_CODE]
		,[FORM_MODULE_ID]
		,[FORM_IS_DELETED]
 from [SECURITY].[FORM]
 where 
 [FORM_IS_DELETED] = 0
 And
 [FORM_CODE] = @P_FORM_CODE
END
