CREATE PROCEDURE [SECURITY].[ModuleGetByParent]
	@P_MODULE_PARENT_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Select 
	[MODULE_ID],
	[MODULE_NAME],
	[MODULE_DESCRIPTION],
	[MODULE_IMAGE],
	[MODULE_IS_DELETED],
	[MODULE_CREATION_DAY],
	[MODULE_CREATION_SEC],
	[MODULE_AlterD_BY],
	[MODULE_PARENT_ID]

	from [SECURITY].[MODULE]
	where
	[MODULE_IS_DELETED] = 0
	AND
	[MODULE_PARENT_ID] = @P_MODULE_PARENT_ID
END
