CREATE PROCEDURE [SECURITY].[RoleUpdate]
	@P_ROLE_ID int,
	@P_ROLE_NAME nvarchar(256),
	@P_ROLE_DESCRIPTION nvarchar(1024),
	@P_ROLE_IS_DELETED bit
AS
BEGIN
	SET NOCOUNT ON;
	UPDATE [SECURITY].[ROLE] SET
		[ROLE_NAME] = @P_ROLE_NAME
		,[ROLE_DESCRIPTION] = @P_ROLE_DESCRIPTION
		,[ROLE_IS_DELETED] = @P_ROLE_IS_DELETED
		
		Where @P_ROLE_ID = @P_ROLE_ID
END
