CREATE PROCEDURE [SECURITY].[RoleGetByID]
	@P_ROLE_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Select 
		[ROLE_ID]
		,[ROLE_NAME]
		,[ROLE_DESCRIPTION]
		,[ROLE_IS_DELETED]
 from [SECURITY].[ROLE]
 where
 [ROLE_IS_DELETED] = 0
 and
 [ROLE_ID] = @P_ROLE_ID
END
