CREATE PROCEDURE [SECURITY].[RoleGetByName]
	@P_ROLE_NAME nvarchar(256)
AS
BEGIN
	SET NOCOUNT ON;
	Select 
		[ROLE_ID]
		,[ROLE_NAME]
		,[ROLE_DESCRIPTION]
		,[ROLE_IS_DELETED]
 from [SECURITY].[ROLE]
 where
 [ROLE_IS_DELETED] = 0
 and
 [ROLE_NAME] = @P_ROLE_NAME
END
