CREATE PROCEDURE [SECURITY].[RoleAdd]
	@P_ROLE_ID int output,
	@P_ROLE_NAME nvarchar(256),
	@P_ROLE_DESCRIPTION nvarchar(1024),
	@P_ROLE_IS_DELETED bit
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [SECURITY].[ROLE]
		(
		[ROLE_NAME]
		,[ROLE_DESCRIPTION]
		,[ROLE_IS_DELETED]
		)
	VALUES
		(
		@P_ROLE_NAME
		,@P_ROLE_DESCRIPTION
		,@P_ROLE_IS_DELETED
		)
		
		set @P_ROLE_ID=SCOPE_IDENTITY()
END
