CREATE PROCEDURE [SECURITY].[UserGetByName]
	@P_USER_NAME nvarchar(1000)
AS
BEGIN
	SET NOCOUNT ON;
	Select 
	[USER_ID]
	,[USER_NAME]
	,[USER_EMAIL]
	,[USER_PASSWORD]
	,[USER_IS_ACTIVE]
	,[USER_CREATION_DAY]
	,[USER_CREATION_SEC]
	,[USER_IS_DELETED]
 from [SECURITY].[USER]
		Where [USER_NAME] = @P_USER_NAME
		and
		[USER_IS_DELETED] = 0
END
