CREATE PROCEDURE [SECURITY].[UserGetByID]
	@P_USER_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Select 
	[USER_ID]
	,[USER_NAME]
	,[USER_EMAIL]
	,[USER_PASSWORD]
	,[USER_IS_ACTIVE]
	,[USER_CREATION_DAY]
	,[USER_CREATION_SEC]
	,[USER_IS_DELETED]
 from [SECURITY].[USER]
		Where [USER_ID] = @P_USER_ID
		and
		[USER_IS_DELETED] = 0
END
