CREATE PROCEDURE [SECURITY].[UserGetNotInForm]
	@P_FORM_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Select 
	u.[USER_ID]
	,u.[USER_NAME]
	,u.[USER_EMAIL]
	,u.[USER_PASSWORD]
	,u.[USER_IS_ACTIVE]
	,u.[USER_CREATION_DAY]
	,u.[USER_CREATION_SEC]
	,u.[USER_IS_DELETED]
 from
 [SECURITY].[USER] u
Where
	not EXISTS(
		select [FORM_USER_ID]
		from
		[SECURITY].[FORM_USER]
		where [FORM_USER_USER_ID] = [USER_ID] and [FORM_USER_FORM_ID] = @P_FORM_ID)	
	and
	u.[USER_IS_DELETED] = 0
END
