CREATE PROCEDURE [SECURITY].[UserGetNotInRole]
	@P_ROLE_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Select 
	u.[USER_ID]
	,u.[USER_NAME]
	,u.[USER_EMAIL]
	,u.[USER_PASSWORD]
	,u.[USER_IS_ACTIVE]
	,u.[USER_CREATION_DAY]
	,u.[USER_CREATION_SEC]
	,u.[USER_IS_DELETED]
 from
 [SECURITY].[USER] u
Where
	not EXISTS(
		select [ROLE_USER_ROLE_ID]
		from
		[SECURITY].[ROLE_USER]
		where [ROLE_USER_USER_ID] = [USER_ID] and [ROLE_USER_ROLE_ID] = @P_ROLE_ID)	
	and
	u.[USER_IS_DELETED] = 0
END
