CREATE PROCEDURE [SECURITY].[UserUpdateActive]
	@P_USER_ID int,
	@P_USER_IS_ACTIVE bit
AS
BEGIN
	SET NOCOUNT ON;
	Update [SECURITY].[USER] SET
		[USER_IS_ACTIVE] = @P_USER_IS_ACTIVE
		Where [USER_ID] = @P_USER_ID
END
