CREATE PROCEDURE [SECURITY].[UserGetAll]
AS
BEGIN
	SET NOCOUNT ON;
	Select 
	[USER_ID]
	,[USER_NAME]
	,[USER_EMAIL]
	,[USER_PASSWORD]
	,[USER_IS_ACTIVE]
	,[USER_CREATION_DAY]
	,[USER_CREATION_SEC]
	,[USER_IS_DELETED]
 from [SECURITY].[USER]
 where [USER_IS_DELETED] = 0
END
