CREATE TABLE [ARTICLE].[ARTICLE] (
    [ARTICLE_ID]            INT             IDENTITY (1, 1) NOT NULL,
    [ARTICLE_NAME]          NVARCHAR (500)  NOT NULL,
    [ARTICLE_DESCRIPTION]   NVARCHAR (1000) NOT NULL,
    [ARTICLE_SUMMARY]       NVARCHAR (1000) NOT NULL,
    [ARTICLE_KEYWORDS]      NVARCHAR (1000) NOT NULL,
    [ARTICLE_SEO_NAME]      NVARCHAR (1000) NOT NULL,
    [ARTICLE_DETAILS]       NTEXT           NOT NULL,
    [ARTICLE_URL]           NVARCHAR (1000) NOT NULL,
    [ARTICLE_IMAGE]         NVARCHAR (500)  NOT NULL,
    [ARTICLE_CATEGORY_ID]   INT             NOT NULL,
    [ARTICLE_CREATION_DAY]  INT             NOT NULL,
    [ARTICLE_CREATION_SEC]  INT             NOT NULL,
    [ARTICLE_IS_DELETED]    BIT             NOT NULL,
    [ARTICLE_PORTAL_ID]     INT             NOT NULL,
    [ARTICLE_LANGUAGE_ID]   INT             NOT NULL,
    [ARTICLE_TYPE]          INT             NOT NULL,
    [ARTICLE_ORDER]         INT             NOT NULL,
    [ARTICLE_CREATED_BY]    INT             NOT NULL,
    [ARTICLE_PARENT_OBJ_ID] INT             NOT NULL,
    [ARTICLE_VIEW_COUNT]    INT             NOT NULL
);

