CREATE TABLE [ECOMMERCE].[COMBINATION_PRODUCT] (
    [COMBINATION_ID]                         INT             IDENTITY (1, 1) NOT NULL,
    [COMBINATION_PRODUCT_ID]                 INT             NOT NULL,
    [COMBINATION_PRODUCT_REFERENCE]          NVARCHAR (500)  NOT NULL,
    [COMBINATION_PRODUCT_EAN13]              NVARCHAR (500)  NOT NULL,
    [COMBINATION_PRODUCT_UPC]                NVARCHAR (500)  NOT NULL,
    [COMBINATION_PRODUCT_SUPPLIER_REFERENCE] INT             NOT NULL,
    [COMBINATION_PRODUCT_WHOLESALE_PRICE]    DECIMAL (18, 2) NOT NULL,
    [COMBINATION_PRODUCT_IMPACT_ON_PRICE]    INT             NOT NULL,
    [COMBINATION_PRODUCT_IMPACT_ON_WEIGHT]   INT             NOT NULL,
    [COMBINATION_PRODUCT_INITIAL_STOCK]      INT             NOT NULL,
    [COMBINATION_PRODUCT_MINIMUM_QUANTITY]   INT             NOT NULL,
    [COMBINATION_PRODUCT_IS_DEFAULT]         BIT             NOT NULL,
    [COMBINATION_PRODUCT_COLOR]              NVARCHAR (500)  NOT NULL,
    [COMBINATION_IS_DELETED]                 BIT             NOT NULL
);

