CREATE TABLE [ECOMMERCE].[ECOMMERCE_LANGUAGE] (
    [ECO_LAN_OBJ_ID]    INT            NOT NULL,
    [ECO_LAN_MODULE_ID] INT            NOT NULL,
    [ECO_LAN_LAN_ID]    INT            NOT NULL,
    [ECO_LAN_NAME]      NVARCHAR (500) NULL,
    [ECO_LAN_DESC]      NVARCHAR (500) NULL,
    [ECO_LAN_KEYWORD]   NVARCHAR (500) NULL,
    [ECO_LAN_NAME2]     NVARCHAR (500) NULL,
    [ECO_LAN_DESC2]     NVARCHAR (500) NULL,
    [ECO_LAN_KEYWORD2]  NVARCHAR (500) NULL,
    [ECO_LAN_DETAILS]   NTEXT          NULL,
    [ECO_LAN_MESSAGE1]  NVARCHAR (500) NULL,
    [ECO_LAN_MESSAGE2]  NVARCHAR (500) NULL,
    [ECO_LAN_MESSAGE3]  NVARCHAR (500) NULL
);

