CREATE TABLE [ECOMMERCE].[GROUP] (
    [GROUP_ID]             INT IDENTITY (1, 1) NOT NULL,
    [GROUP_IS_COLOR_GROUP] BIT NOT NULL,
    [GROUP_IS_DELETED]     BIT NOT NULL,
    [GROUP_PORTAL_ID]      INT NOT NULL
);

