CREATE TABLE [ECOMMERCE].[MANUFACTURARE] (
    [MANUFACTURARE_ID]         INT            IDENTITY (1, 1) NOT NULL,
    [MANUFACTURARE_LOGO_IMAGE] NVARCHAR (500) NOT NULL,
    [MANUFACTURARE_IS_ENABLED] BIT            NOT NULL,
    [MANUFACTURARE_IS_DELETED] BIT            NOT NULL,
    [MANUFACTURARE_PORTAL_ID]  INT            NOT NULL
);

