CREATE TABLE [ECOMMERCE].[PREFERENCE] (
    [PREFERENCE_ID]         INT            IDENTITY (1, 1) NOT NULL,
    [PREFERENCE_NAME]       NVARCHAR (200) NOT NULL,
    [PREFERENCE_PORTAL_ID]  INT            NOT NULL,
    [PREFERENCE_IS_ENABLED] BIT            NOT NULL
);

