CREATE TABLE [ECOMMERCE].[SUPPLIER] (
    [SUPPLIER_ID]            INT            IDENTITY (1, 1) NOT NULL,
    [SUPPLIER_LOGO_IMAGE]    NVARCHAR (100) NOT NULL,
    [SUPPLIER_IS_ENABLED]    BIT            NOT NULL,
    [SUPPLIER_PARENT_OBJ_ID] INT            NOT NULL,
    [SUPPLIER_IS_DELETED]    BIT            NOT NULL,
    [SUPPLIER_PORTAL_ID]     INT            NOT NULL
);

