-- Created By : Qasem Hammouri
-- Cration Date : March 31,2013

CREATE TABLE [ECOMMERCE].[COUNTRY]
(
[COUNTRY_ID] int NOT NULL IDENTITY(1, 1),
[COUNTRY_NAME] nvarchar (250)  NOT NULL
)
go
ALTER TABLE [ECOMMERCE].[COUNTRY] ADD CONSTRAINT [PK_ECOMMERCE.COUNTRY] PRIMARY KEY CLUSTERED  ([COUNTRY_ID])