-- Created By : Qasem Hammouri
-- Cration Date : March 31,2013

IF (NOT EXISTS (SELECT 1 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_SCHEMA = 'ECOMMERCE' 
                 AND  TABLE_NAME = 'ORDER'))
BEGIN
    --Do Stuff

CREATE TABLE [ECOMMERCE].[ORDER]
(
[ORDER_ID] int NOT NULL IDENTITY(1, 1),
[ORDER_CUSTOMER_ID] INT NOT NULL,
[ORDER_CREATED_ON] DATETIME NOT NULL,
[ORDER_STATUS] INT DEFAULT(1) NOT NULL,
[ORDER_TOTAL_AMOUNT] INT NOT NULL,
[XREF_ODER] INT NULL

)
ALTER TABLE [ECOMMERCE].[ORDER] ADD CONSTRAINT [PK_ECOMMERCE.ORDER] PRIMARY KEY CLUSTERED  ([ORDER_ID])
END

GO

IF (NOT EXISTS (SELECT 1 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_SCHEMA = 'ECOMMERCE' 
                 AND  TABLE_NAME = 'ORDER_DETAILS'))
BEGIN
CREATE TABLE [ECOMMERCE].[ORDER_DETAILS]
(
[ORDER_DETAILS_ID] int NOT NULL IDENTITY(1, 1),
[ORDER_DETAILS_ORDER_ID] INT NOT NULL,
[ORDER_DETAILS_AMOUNT] INT NOT NULL,
[ORDER_DETAILS_PRODUCT_ID] INT NOT NULL,
[ORDER_DETAILS_CATEGORY_ID] INT NOT NULL,
[ORDER_DETAILS_CREATED_ON] DATETIME NOT NULL,
[ORDER_DETAILS_STATUS] INT DEFAULT(1) NOT NULL,
[ORDER_DETAILS_XREF_ORDER_DETAILS] INT NULL

)
ALTER TABLE [ECOMMERCE].[ORDER_DETAILS] ADD CONSTRAINT [PK_ECOMMERCE.ORDER_DETAILS] PRIMARY KEY CLUSTERED  ([ORDER_DETAILS_ID])
END

IF (NOT EXISTS (SELECT 1 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_SCHEMA = 'ECOMMERCE' 
                 AND  TABLE_NAME = 'ORDER_PRODUCT_DETAILS'))
BEGIN
CREATE TABLE [ECOMMERCE].[ORDER_PRODUCT_DETAILS]
(
[ORD_PRO_DET_ID] int NOT NULL IDENTITY(1, 1),
[ORD_PRO_DET_PRODUCT_ID] INT NOT NULL,
[ORD_PRO_DET_ATTRIBUTE_ID] INT NOT NULL,
[ORD_PRO_DET_DETAILS_ID] INT NOT NULL,
[ORD_PRO_DET_XREF_PRODUCT_DETAILS] INT NULL

)
ALTER TABLE [ECOMMERCE].[ORDER_PRODUCT_DETAILS] ADD CONSTRAINT [PK_ECOMMERCE.ORDER_PRODUCT_DETAILS] PRIMARY KEY CLUSTERED  ([ORD_PRO_DET_ID])
END
