-- Created By : Qasem Hammouri
-- Cration Date : March 31,2013
IF not EXISTS (SELECT 1 
                 FROM INFORMATION_SCHEMA.TABLES  
                   WHERE TABLE_SCHEMA = 'ECOMMERCE' 
                 AND  TABLE_NAME = 'PRODUCT_ATTRIBUTE')
BEGIN
    

CREATE TABLE [ECOMMERCE].[PRODUCT_ATTRIBUTE]
(
[PRODUCT_ATTRIBUTE_ID] int NOT NULL IDENTITY(1, 1),
[PRO_ATT_ATTRIBUTE_ID] int   NOT NULL,
[PRO_ATT_PRODUCT_ID] int   NOT NULL,
[PRO_ATT_DETAILS] nvarchar(max)  default('')

)
ALTER TABLE [ECOMMERCE].[PRODUCT_ATTRIBUTE] ADD CONSTRAINT [PK_ECOMMERCE.PRODUCT_ATTRIBUTE] PRIMARY KEY CLUSTERED  ([PRODUCT_ATTRIBUTE_ID])
END