CREATE PROCEDURE [GALLERY].[GalleryAdd]
	@P_GALLERY_ID int output,
    @P_GALLERY_NAME nvarchar(500),
    @P_GALLERY_DESCRIPTION nvarchar(1000),
    @P_GALLERY_SUMMARY nvarchar(1000),
	@P_GALLERY_KEYWORDS nvarchar(1000),
	@P_GALLERY_SEO_NAME nvarchar(1000),
	@P_GALLERY_DETAILS ntext,
    @P_GALLERY_URL nvarchar(1000),
	@P_GALLERY_FILE nvarchar(500),	
	@P_GALLERY_CATEGORY_ID int,
	@P_GALLERY_CREATION_DAY int,
	@P_GALLERY_CREATION_SEC int,
	@P_GALLERY_IS_DELETED bit,
	@P_GALLERY_PORTAL_ID int,
	@P_GALLERY_LANGUAGE_ID int,
	@P_GALLERY_TYPE int,
	@P_GALLERY_ITEM_TYPE int,
	@P_GALLERY_ORDER int,
	@P_GALLERY_CREATED_BY int,
	@P_GALLERY_PARENT_OBJ_ID int
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [GALLERY].[GALLERY]
		(
		[GALLERY_NAME]
		,[GALLERY_DESCRIPTION]
		,[GALLERY_KEYWORDS]
		,[GALLERY_SEO_NAME]
		,[GALLERY_DETAILS]
		,[GALLERY_URL]
		,[GALLERY_FILE]
		,[GALLERY_SUMMARY]
		,[GALLERY_CATEGORY_ID]
		,[GALLERY_CREATION_DAY]
		,[GALLERY_CREATION_SEC]
		,[GALLERY_IS_DELETED]
		,[GALLERY_PORTAL_ID]
		,[GALLERY_LANGUAGE_ID]
		,[GALLERY_TYPE]
		,[GALLERY_ITEM_TYPE]
		,[GALLERY_ORDER]
		,[GALLERY_CREATED_BY]
		,[GALLERY_PARENT_OBJ_ID]
		)
	VALUES
		(
		@P_GALLERY_NAME,
		@P_GALLERY_DESCRIPTION,
		@P_GALLERY_KEYWORDS,
		@P_GALLERY_SEO_NAME,
		@P_GALLERY_DETAILS,
		@P_GALLERY_URL,
		@P_GALLERY_FILE,
		@P_GALLERY_SUMMARY,
		@P_GALLERY_CATEGORY_ID,
		@P_GALLERY_CREATION_DAY,
		@P_GALLERY_CREATION_SEC,
		@P_GALLERY_IS_DELETED,
		@P_GALLERY_PORTAL_ID,
		@P_GALLERY_LANGUAGE_ID,
		@P_GALLERY_TYPE,
		@P_GALLERY_ITEM_TYPE,
		@P_GALLERY_ORDER,
		@P_GALLERY_CREATED_BY,
		@P_GALLERY_PARENT_OBJ_ID
		)
		
		set @P_GALLERY_ID=SCOPE_IDENTITY()
END
