CREATE PROCEDURE [GALLERY].[GalleryDeleteLogical]
	@P_GALLERY_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Update [GALLERY].[GALLERY] set
	[GALLERY_IS_DELETED]=1
	Where 
	GALLERY_ID=@P_GALLERY_ID
	or
	GALLERY_PARENT_OBJ_ID = @P_GALLERY_ID
END
