CREATE PROCEDURE [GALLERY].[GalleryGetByCategoryXML]
	@P_GALLERY_CATEGORY_ID int,
	@P_GALLERY_TYPE int,
	@P_ROW_FROM int,
	@P_ROW_TO int,
	@P_TOTAL_COUNT int output,
	@P_PUBLISH_MODULE_ID int,
	@P_PUBLISH_TYPE_ID int
AS
BEGIN
	SET NOCOUNT ON;
	
	Select @P_TOTAL_COUNT = Count(1) from 
			[GALLERY].[GALLERY]
			INNER JOIN
			[SETUP].[PUBLISH]
			ON 
				[GALLERY_ID] = [PUBLISH_OBJECT_ID]
				AND	
				[GALLERY_PORTAL_ID] = [PUBLISH_PORTAL_ID]
				AND
				[GALLERY_LANGUAGE_ID] = [PUBLISH_LANGUAGE_ID] 
				AND
				[PUBLISH_MODULE_ID] = @P_PUBLISH_MODULE_ID
				AND
				[PUBLISH_TYPE_ID] = @P_PUBLISH_TYPE_ID
			where
				[GALLERY_CATEGORY_ID] = @P_GALLERY_CATEGORY_ID
				AND
				[GALLERY_TYPE] = @P_GALLERY_TYPE
				AND
				[GALLERY_IS_DELETED] = 0
			
	Select 
		[GALLERY_ID],
		[GALLERY_NAME],
		[GALLERY_DESCRIPTION],
		[GALLERY_KEYWORDS],
		[GALLERY_SEO_NAME],
		[GALLERY_URL],
		[GALLERY_FILE],
		[GALLERY_SUMMARY],
		[GALLERY_CATEGORY_ID],
		[GALLERY_CREATION_DAY],
		[GALLERY_CREATION_SEC],
		[GALLERY_IS_DELETED],
		[GALLERY_PORTAL_ID],
		[GALLERY_LANGUAGE_ID],
		[GALLERY_TYPE],
		[GALLERY_ITEM_TYPE],
		[GALLERY_ORDER],
		[GALLERY_CREATED_BY],
		[GALLERY_PARENT_OBJ_ID]
	From
	(
		Select 
			[GALLERY_ID],
			[GALLERY_NAME],
			[GALLERY_DESCRIPTION],
			[GALLERY_KEYWORDS],
			[GALLERY_SEO_NAME],
			[GALLERY_URL],
			[GALLERY_FILE],
			[GALLERY_SUMMARY],
			[GALLERY_CATEGORY_ID],
			[GALLERY_CREATION_DAY],
			[GALLERY_CREATION_SEC],
			[GALLERY_IS_DELETED],
			[GALLERY_PORTAL_ID],
			[GALLERY_LANGUAGE_ID],
			[GALLERY_TYPE],
			[GALLERY_ITEM_TYPE],
			[GALLERY_ORDER],
			[GALLERY_CREATED_BY],
			[GALLERY_PARENT_OBJ_ID],
			Row_Number() over(order by [GALLERY_ORDER],[GALLERY_CREATION_DAY] DESC,[GALLERY_CREATION_SEC] DESC) As [RowNumber]
		 From
			[GALLERY].[GALLERY]
			INNER JOIN
			[SETUP].[PUBLISH]
			ON 
				[GALLERY_ID] = [PUBLISH_OBJECT_ID]
				AND	
				[GALLERY_PORTAL_ID] = [PUBLISH_PORTAL_ID]
				AND
				[GALLERY_LANGUAGE_ID] = [PUBLISH_LANGUAGE_ID] 
				AND
				[PUBLISH_MODULE_ID] = @P_PUBLISH_MODULE_ID
				AND
				[PUBLISH_TYPE_ID] = @P_PUBLISH_TYPE_ID
			where
				[GALLERY_CATEGORY_ID] = @P_GALLERY_CATEGORY_ID
				AND
				[GALLERY_TYPE] = @P_GALLERY_TYPE
				AND
				[GALLERY_IS_DELETED] = 0
	) As Item
	Where [RowNumber] Between @P_ROW_FROM AND @P_ROW_TO
	
	For XML AUTO,TYPE,ROOT('Parent')
END
