CREATE PROCEDURE [GALLERY].[GalleryGetParentObjByCategory]
	@P_GALLERY_CATEGORY_ID int,
	@P_GALLERY_TYPE int,
	@P_PUBLISH_MODULE_ID int	
AS
BEGIN
	SET NOCOUNT ON;
	Select 
	G.[GALLERY_ID],
	G.[GALLERY_NAME],
	G.[GALLERY_DESCRIPTION],
	G.[GALLERY_KEYWORDS],
	G.[GALLERY_SEO_NAME],
	G.[GALLERY_DETAILS],
	G.[GALLERY_URL],
	G.[GALLERY_FILE],
	G.[GALLERY_SUMMARY],
	G.[GALLERY_CATEGORY_ID],
	G.[GALLERY_CREATION_DAY],
	G.[GALLERY_CREATION_SEC],
	G.[GALLERY_IS_DELETED],
	G.[GALLERY_PORTAL_ID],
	G.[GALLERY_LANGUAGE_ID],
	G.[GALLERY_TYPE],
	G.[GALLERY_ITEM_TYPE],
	G.[GALLERY_ORDER],
	G.[GALLERY_CREATED_BY],
	G.[GALLERY_PARENT_OBJ_ID],
	P.[PUBLISH_TYPE_ID]
 from [GALLERY].[GALLERY] AS G
	LEFT OUTER JOIN
	[SETUP].[PUBLISH] AS P
	ON
	G.[GALLERY_LANGUAGE_ID]= P.[PUBLISH_LANGUAGE_ID]
	AND
	G.[GALLERY_PORTAL_ID] = P.[PUBLISH_PORTAL_ID]
	AND
	G.[GALLERY_ID] = P.[PUBLISH_OBJECT_ID]
	AND
	P.[PUBLISH_MODULE_ID] = @P_PUBLISH_MODULE_ID
	where
	[GALLERY_CATEGORY_ID] = @P_GALLERY_CATEGORY_ID
	and
	[GALLERY_TYPE] = @P_GALLERY_TYPE
	and
	[GALLERY_PARENT_OBJ_ID] = 0
	and
	[GALLERY_IS_DELETED] = 0
	order by [GALLERY_ORDER],[GALLERY_CREATION_DAY],[GALLERY_CREATION_SEC],[GALLERY_ID]
END
