CREATE PROCEDURE [GALLERY].[GalleryDelete]
	@P_GALLERY_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Delete from [GALLERY].[GALLERY] 
		Where 
		GALLERY_ID=@P_GALLERY_ID
		or
		GALLERY_PARENT_OBJ_ID = @P_GALLERY_ID
END
