CREATE PROCEDURE [SETUP].[CategoryUpdate]
	@P_CATEGORY_ID int,
	@P_CATEGORY_NAME nvarchar(500),
	@P_CATEGORY_DESCRIPTION nvarchar(1000),
	@P_CATEGORY_MODULE_ID int,
	@P_CATEGORY_IS_DELETED bit,
	@P_CATEGORY_PORTAL_ID int,
	@P_CATEGORY_LANGUAGE_ID int,
	@P_CATEGORY_CREATION_DAY int,
	@P_CATEGORY_CREATION_SEC int,
	@P_CATEGORY_PARENT_ID int,
	@P_CATEGORY_ORDER int,
	@P_CATEGORY_CREATED_BY int,
	@P_CATEGORY_IMAGE nvarchar(500)
AS
BEGIN
	SET NOCOUNT ON;
	Update [SETUP].[CATEGORY] SET
		[CATEGORY_NAME] = @P_CATEGORY_NAME
		,[CATEGORY_DESCRIPTION] = @P_CATEGORY_DESCRIPTION
		,[CATEGORY_MODULE_ID] = @P_CATEGORY_MODULE_ID
		,[CATEGORY_IS_DELETED] = @P_CATEGORY_IS_DELETED
		,[CATEGORY_PORTAL_ID] = @P_CATEGORY_PORTAL_ID
		,[CATEGORY_LANGUAGE_ID] = @P_CATEGORY_LANGUAGE_ID
		,[CATEGORY_CREATION_DAY] = @P_CATEGORY_CREATION_DAY
		,[CATEGORY_CREATION_SEC] = @P_CATEGORY_CREATION_SEC
		,[CATEGORY_PARENT_ID] = @P_CATEGORY_PARENT_ID
		,[CATEGORY_ORDER] = @P_CATEGORY_ORDER
		,[CATEGORY_CREATED_BY] = @P_CATEGORY_CREATED_BY
		,[CATEGORY_IMAGE] = @P_CATEGORY_IMAGE
		Where [CATEGORY_ID] = @P_CATEGORY_ID
END
