CREATE PROCEDURE [SETUP].[CMSControlGetByID]
	@P_CMSCONTROL_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Select 
	[CMSCONTROL_ID]
	,[CMSCONTROL_NAME]
	,[CMSCONTROL_DESCRIPTION]
	,[CMSCONTROL_USER_CONTROL_PATH]
	,[CMSCONTROL_MODULE_ID]
	,[CMSCONTROL_IS_DELETED]
	,[CMSCONTROL_CREATION_DAY]
	,[CMSCONTROL_CREATION_SEC]
	,[CMSCONTROL_CREATED_BY]
 from [SETUP].[CMSCONTROL]
		Where [CMSCONTROL_ID] = @P_CMSCONTROL_ID
		and
		[CMSCONTROL_IS_DELETED] = 0
END
