CREATE PROCEDURE [SETUP].[CMSControlUpdate]
	@P_CMSCONTROL_ID int,
	@P_CMSCONTROL_NAME nvarchar(500),
	@P_CMSCONTROL_DESCRIPTION nvarchar(1000),
	@P_CMSCONTROL_USER_CONTROL_PATH nvarchar(1000),
	@P_CMSCONTROL_MODULE_ID int,
	@P_CMSCONTROL_IS_DELETED bit,
	@P_CMSCONTROL_CREATION_DAY int,
	@P_CMSCONTROL_CREATION_SEC int,
	@P_CMSCONTROL_CREATED_BY int
AS
BEGIN
	SET NOCOUNT ON;
	Update [SETUP].[CMSCONTROL] SET
		[CMSCONTROL_NAME] = @P_CMSCONTROL_NAME
		,[CMSCONTROL_DESCRIPTION] = @P_CMSCONTROL_DESCRIPTION
		,[CMSCONTROL_USER_CONTROL_PATH] = @P_CMSCONTROL_USER_CONTROL_PATH
		,[CMSCONTROL_MODULE_ID] = @P_CMSCONTROL_MODULE_ID
		,[CMSCONTROL_IS_DELETED] = @P_CMSCONTROL_IS_DELETED
		,[CMSCONTROL_CREATION_DAY] = @P_CMSCONTROL_CREATION_DAY
		,[CMSCONTROL_CREATION_SEC] = @P_CMSCONTROL_CREATION_SEC
		,[CMSCONTROL_CREATED_BY] = @P_CMSCONTROL_CREATED_BY
		Where [CMSCONTROL_ID] = @P_CMSCONTROL_ID
END
