CREATE PROCEDURE [SETUP].[CMSControlDeleteLogical]
	@P_CMSCONTROL_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Update [SETUP].[CMSCONTROL] set
	[CMSCONTROL_IS_DELETED] = 1
	Where [CMSCONTROL_ID] = @P_CMSCONTROL_ID
END
