CREATE PROCEDURE [SETUP].[HtmlBlockAdd]
	@P_HTMLBLOCK_ID int output,
	@P_HTMLBLOCK_NAME nvarchar(500),
	@P_HTMLBLOCK_DETAILS ntext,
	@P_HTMLBLOCK_IS_DELETED bit,
	@P_HTMLBLOCK_PORTAL_ID int,
	@P_HTMLBLOCK_LANGUAGE_ID int,
	@P_HTMLBLOCK_CREATION_DAY int,
	@P_HTMLBLOCK_CREATION_SEC int,
	@P_HTMLBLOCK_CREATED_BY int
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [SETUP].[HTMLBLOCK]
		(
		[HTMLBLOCK_NAME]
		,[HTMLBLOCK_DETAILS]
		,[HTMLBLOCK_IS_DELETED]
		,[HTMLBLOCK_PORTAL_ID]
		,[HTMLBLOCK_LANGUAGE_ID]
		,[HTMLBLOCK_CREATION_DAY]
		,[HTMLBLOCK_CREATION_SEC]
		,[HTMLBLOCK_CREATED_BY]
		)
	VALUES
		(
		@P_HTMLBLOCK_NAME,
		@P_HTMLBLOCK_DETAILS,
		@P_HTMLBLOCK_IS_DELETED,
		@P_HTMLBLOCK_PORTAL_ID,
		@P_HTMLBLOCK_LANGUAGE_ID,
		@P_HTMLBLOCK_CREATION_DAY,
		@P_HTMLBLOCK_CREATION_SEC,
		@P_HTMLBLOCK_CREATED_BY
		)
		
		set @P_HTMLBLOCK_ID=SCOPE_IDENTITY()
END
