CREATE PROCEDURE [SETUP].[HtmlBlockDeleteLogical]
	@P_HTMLBLOCK_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Update [SETUP].[HTMLBLOCK] set
	[HTMLBLOCK_IS_DELETED] = 1
	Where [HTMLBLOCK_ID] = @P_HTMLBLOCK_ID
END
