CREATE PROCEDURE [SETUP].[LanguageAdd]

@P_LANGUAGE_ID int output,
@P_LANGUAGE_NAME nvarchar(100),
@P_LANGUAGE_CULTURE nvarchar(50),
@P_LANGUAGE_IMAGE nvarchar(500)

AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [SETUP].[LANGUAGE]
		(
			LANGUAGE_NAME,
			LANGUAGE_CULTURE,
			LANGUAGE_IMAGE
		)
	VALUES
		(
			@P_LANGUAGE_NAME,
			@P_LANGUAGE_CULTURE,
			@P_LANGUAGE_IMAGE
		)
		
		set @P_LANGUAGE_ID = SCOPE_IDENTITY()
END
