CREATE PROCEDURE [SETUP].[LanguageGetByPortalID]

@P_PORTAL_ID INT

AS
BEGIN
	SET NOCOUNT ON;
	SELECT
		L.LANGUAGE_ID,
		L.LANGUAGE_NAME,
		L.LANGUAGE_CULTURE,
		L.LANGUAGE_IMAGE
		
	FROM [SETUP].[LANGUAGE] AS L
		INNER JOIN
		[SETUP].PORTAL_LANGUAGE AS PL
		ON PL.LANGUAGE_ID = L.LANGUAGE_ID AND PL.PORTAL_ID = @P_PORTAL_ID
	
END
