CREATE PROCEDURE [SETUP].[LanguageUpdate]

@P_LANGUAGE_ID int,
@P_LANGUAGE_NAME nvarchar(100),
@P_LANGUAGE_CULTURE nvarchar(50),
@P_LANGUAGE_IMAGE nvarchar(500)

AS
BEGIN
	SET NOCOUNT ON;
	UPDATE [SETUP].[LANGUAGE] SET
	
		
			LANGUAGE_NAME = @P_LANGUAGE_NAME,
			LANGUAGE_CULTURE = @P_LANGUAGE_CULTURE,
			LANGUAGE_IMAGE = @P_LANGUAGE_IMAGE
	WHERE 		
		    LANGUAGE_ID = @P_LANGUAGE_ID 
END
