CREATE PROCEDURE [SETUP].[LanguageUrlGetAll]
@P_LANGUAGE_URL_PORTAL_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Select 
	LANGUAGE_URL_ID,
	LANGUAGE_URL_LANGUAGE_ID,
	LANGUAGE_URL_NAME,
	LANGUAGE_URL_PORTAL_ID
	
 from [SETUP].[LANGUAGE_URL]
 where 
 LANGUAGE_URL_PORTAL_ID = @P_LANGUAGE_URL_PORTAL_ID
 

END
