CREATE PROCEDURE [SETUP].[MenuDeleteLogical]
	@P_MENU_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Update [SETUP].[MENU] set
	[MENU_IS_DELETED]=1
	Where
	MENU_ID = @P_MENU_ID
	or
	MENU_PARENT_OBJ_ID = @P_MENU_ID 
END
