CREATE PROCEDURE [SETUP].[MenuAdd]
	@P_MENU_ID int output,
    @P_MENU_NAME nvarchar(500),
    @P_MENU_DESCRIPTION nvarchar(1000),
	@P_MENU_KEYWORDS nvarchar(1000),
	@P_MENU_SEO_NAME nvarchar(1000),
	@P_MENU_DETAILS ntext,
    @P_MENU_URL nvarchar(1000),
	@P_MENU_IMAGE nvarchar(500),
	@P_MENU_PAGE_ID int,
	@P_MENU_CATEGORY_ID int,
	@P_MENU_PARENT_ID int,
	@P_MENU_CREATION_DAY int,
	@P_MENU_CREATION_SEC int,
	@P_MENU_IS_DELETED bit,
	@P_MENU_PORTAL_ID int,
	@P_MENU_LANGUAGE_ID int,
	@P_MENU_TYPE int,
	@P_MENU_ORDER int,
	@P_MENU_CREATED_BY int,
	@P_MENU_PARENT_OBJ_ID int
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [SETUP].[MENU]
		(
		[MENU_NAME]
		,[MENU_DESCRIPTION]
		,[MENU_KEYWORDS]
		,[MENU_SEO_NAME]
		,[MENU_DETAILS]
		,[MENU_URL]
		,[MENU_IMAGE]
		,[MENU_PAGE_ID]
		,[MENU_CATEGORY_ID]
		,[MENU_PARENT_ID]
		,[MENU_CREATION_DAY]
		,[MENU_CREATION_SEC]
		,[MENU_IS_DELETED]
		,[MENU_PORTAL_ID]
		,[MENU_LANGUAGE_ID]
		,[MENU_TYPE]
		,[MENU_ORDER]
		,[MENU_CREATED_BY]
		,[MENU_PARENT_OBJ_ID]
		)
	VALUES
		(
		@P_MENU_NAME,
		@P_MENU_DESCRIPTION,
		@P_MENU_KEYWORDS,
		@P_MENU_SEO_NAME,
		@P_MENU_DETAILS,
		@P_MENU_URL,
		@P_MENU_IMAGE,
		@P_MENU_PAGE_ID,
		@P_MENU_CATEGORY_ID,
		@P_MENU_PARENT_ID,
		@P_MENU_CREATION_DAY,
		@P_MENU_CREATION_SEC,
		@P_MENU_IS_DELETED,
		@P_MENU_PORTAL_ID,
		@P_MENU_LANGUAGE_ID,
		@P_MENU_TYPE,
		@P_MENU_ORDER,
		@P_MENU_CREATED_BY,
		@P_MENU_PARENT_OBJ_ID
		)
		
		set @P_MENU_ID=SCOPE_IDENTITY()
END
