CREATE PROCEDURE [SETUP].[MenuGetByParentObjID]
	@P_MENU_PARENT_OBJ_ID int,
	@P_MENU_LANGUAGE_ID int,
	@P_PUBLISH_MODULE_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Select 
	[MENU_ID],
	[MENU_NAME],
	[MENU_DESCRIPTION],
	[MENU_KEYWORDS],
	[MENU_SEO_NAME],
	[MENU_DETAILS],
	[MENU_URL],
	[MENU_IMAGE],
	[MENU_PAGE_ID],
	[MENU_CATEGORY_ID],
	[MENU_PARENT_ID],
	[MENU_CREATION_DAY],
	[MENU_CREATION_SEC],
	[MENU_IS_DELETED],
	[MENU_PORTAL_ID],
	[MENU_LANGUAGE_ID],
	[MENU_TYPE],
	[MENU_ORDER],
	[MENU_CREATED_BY],
	[MENU_PARENT_OBJ_ID]
 from [SETUP].[MENU] AS M
  
	where
	[MENU_PARENT_OBJ_ID] = @P_MENU_PARENT_OBJ_ID
	and
	[MENU_LANGUAGE_ID] = @P_MENU_LANGUAGE_ID
	
	and
	[MENU_IS_DELETED] = 0
	
END
