CREATE PROCEDURE [SETUP].[PageUpdate]
	@P_PAGE_ID int,
	@P_PAGE_NAME nvarchar(500),
	@P_PAGE_TITLE nvarchar(500),
	@P_PAGE_DESCRIPTION nvarchar(1000),
	@P_PAGE_KEYWORDS nvarchar(1000),
	@P_PAGE_SEO_NAME nvarchar(1000),
	@P_PAGE_ICON nvarchar(500),
	@P_PAGE_DETAILS ntext,
	@P_PAGE_CREATION_DAY int,
	@P_PAGE_CREATION_SEC int,
	@P_PAGE_IS_DELETED bit,
	@P_PAGE_TYPE int,
	@P_PAGE_TEMPLATE_ID int,
	@P_PAGE_PORTAL_ID int,
	@P_PAGE_LANGUAGE_ID int,
	@P_PAGE_CREATED_BY int
AS
BEGIN
	SET NOCOUNT ON;
	Update [SETUP].[PAGE] SET
		[PAGE_NAME] = @P_PAGE_NAME
		,[PAGE_TITLE] = @P_PAGE_TITLE
		,[PAGE_DESCRIPTION] = @P_PAGE_DESCRIPTION
		,[PAGE_KEYWORDS] = @P_PAGE_KEYWORDS
		,[PAGE_SEO_NAME] = @P_PAGE_SEO_NAME
		,[PAGE_ICON] = @P_PAGE_ICON
		,[PAGE_DETAILS] = @P_PAGE_DETAILS
		,[PAGE_CREATION_DAY] = @P_PAGE_CREATION_DAY
		,[PAGE_CREATION_SEC] = @P_PAGE_CREATION_SEC
		,[PAGE_IS_DELETED] = @P_PAGE_IS_DELETED
		,[PAGE_TYPE] = @P_PAGE_TYPE
		,[PAGE_TEMPLATE_ID] = @P_PAGE_TEMPLATE_ID
		,[PAGE_LANGUAGE_ID] = @P_PAGE_LANGUAGE_ID
		,[PAGE_PORTAL_ID] = @P_PAGE_PORTAL_ID
		,[PAGE_CREATED_BY] = @P_PAGE_CREATED_BY
		Where PAGE_ID = @P_PAGE_ID
END
