CREATE PROCEDURE [SETUP].[PageGetByID]
	@P_PAGE_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Select 
	[PAGE_ID]
	,[PAGE_NAME]
	,[PAGE_TITLE]
	,[PAGE_DESCRIPTION]
	,[PAGE_KEYWORDS]
	,[PAGE_SEO_NAME]
	,[PAGE_ICON]
	,[PAGE_DETAILS]
	,[PAGE_CREATION_DAY]
	,[PAGE_CREATION_SEC]
	,[PAGE_IS_DELETED]
	,[PAGE_TYPE]
	,[PAGE_TEMPLATE_ID]
	,[PAGE_LANGUAGE_ID]
	,[PAGE_PORTAL_ID]
	,[PAGE_CREATED_BY]
 from [SETUP].[PAGE]
 where 
	[PAGE_IS_DELETED] = 0
	and
	[PAGE_ID] = @P_PAGE_ID
END
