CREATE PROCEDURE [SETUP].[PublishAdd]
	@P_PUBLISH_ID int output,
	@P_PUBLISH_MODULE_ID int,
	@P_PUBLISH_OBJECT_ID int,
	@P_PUBLISH_TYPE_ID int,
	@P_PUBLISH_FROM_DAY int,
	@P_PUBLISH_FROM_SEC bit,
	@P_PUBLISH_TO_DAY int,
	@P_PUBLISH_TO_SEC int,
	@P_PUBLISH_CREATED_BY int,
	@P_PUBLISH_PORTAL_ID int,
	@P_PUBLISH_LANGUAGE_ID int
AS
BEGIN
	SET NOCOUNT ON;
	
	DECLARE @COUNT INT;
	
	SELECT @COUNT = COUNT(1) FROM [SETUP].[PUBLISH] WHERE 
	[PUBLISH_OBJECT_ID] = @P_PUBLISH_OBJECT_ID
	and 
	[PUBLISH_LANGUAGE_ID] = @P_PUBLISH_LANGUAGE_ID
	and
	[PUBLISH_PORTAL_ID] = @P_PUBLISH_PORTAL_ID
	and
	[PUBLISH_MODULE_ID] = @P_PUBLISH_MODULE_ID
	
	IF @COUNT <= 0 
	BEGIN
	INSERT INTO [SETUP].[PUBLISH]
		(
		[PUBLISH_MODULE_ID]
		,[PUBLISH_OBJECT_ID]
		,[PUBLISH_TYPE_ID]
		,[PUBLISH_FROM_DAY]
		,[PUBLISH_FROM_SEC]
		,[PUBLISH_TO_DAY]
		,[PUBLISH_TO_SEC]
		,[PUBLISH_CREATED_BY]
		,[PUBLISH_PORTAL_ID]
		,[PUBLISH_LANGUAGE_ID]
		)
	VALUES
		(
		@P_PUBLISH_MODULE_ID,
		@P_PUBLISH_OBJECT_ID,
		@P_PUBLISH_TYPE_ID,
		@P_PUBLISH_FROM_DAY,
		@P_PUBLISH_FROM_SEC,
		@P_PUBLISH_TO_DAY,
		@P_PUBLISH_TO_SEC,
		@P_PUBLISH_CREATED_BY,
		@P_PUBLISH_PORTAL_ID,
		@P_PUBLISH_LANGUAGE_ID
		)
		set @P_PUBLISH_ID=SCOPE_IDENTITY()
		END
END
