CREATE PROCEDURE [SETUP].[PublishGetByID]
	@P_PUBLISH_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Select 
	[PUBLISH_ID]
	,[PUBLISH_MODULE_ID]
	,[PUBLISH_OBJECT_ID]
	,[PUBLISH_TYPE_ID]
	,[PUBLISH_FROM_DAY]
	,[PUBLISH_FROM_SEC]
	,[PUBLISH_TO_DAY]
	,[PUBLISH_TO_SEC]
	,[PUBLISH_CREATED_BY]
	,[PUBLISH_PORTAL_ID]
	,[PUBLISH_LANGUAGE_ID]
 from [SETUP].[PUBLISH]
		Where [PUBLISH_ID] = @P_PUBLISH_ID
END
