CREATE PROCEDURE [SETUP].[PublishUpdate]
	@P_PUBLISH_ID int,
	@P_PUBLISH_MODULE_ID int,
	@P_PUBLISH_OBJECT_ID int,
	@P_PUBLISH_TYPE_ID int,
	@P_PUBLISH_FROM_DAY int,
	@P_PUBLISH_FROM_SEC bit,
	@P_PUBLISH_TO_DAY int,
	@P_PUBLISH_TO_SEC int,
	@P_PUBLISH_CREATED_BY int,
	@P_PUBLISH_PORTAL_ID int,
	@P_PUBLISH_LANGUAGE_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Update [SETUP].[PUBLISH] SET
		[PUBLISH_MODULE_ID] = @P_PUBLISH_MODULE_ID
		,[PUBLISH_OBJECT_ID] = @P_PUBLISH_OBJECT_ID
		,[PUBLISH_TYPE_ID] = @P_PUBLISH_TYPE_ID
		,[PUBLISH_FROM_DAY] = @P_PUBLISH_FROM_DAY
		,[PUBLISH_FROM_SEC] = @P_PUBLISH_FROM_SEC
		,[PUBLISH_TO_DAY] = @P_PUBLISH_TO_DAY
		,[PUBLISH_TO_SEC] = @P_PUBLISH_TO_SEC
		,[PUBLISH_CREATED_BY] = @P_PUBLISH_CREATED_BY
		,[PUBLISH_PORTAL_ID] = @P_PUBLISH_PORTAL_ID
		,[PUBLISH_LANGUAGE_ID] = @P_PUBLISH_LANGUAGE_ID
		Where [PUBLISH_ID] = @P_PUBLISH_ID
END
