CREATE PROCEDURE [SETUP].[PublishGetByModuleID]
	@P_PUBLISH_MODULE_ID int,
	@P_PUBLISH_PORTAL_ID int,
	@P_PUBLISH_LANGUAGE_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Select 
	[PUBLISH_ID]
	,[PUBLISH_MODULE_ID]
	,[PUBLISH_OBJECT_ID]
	,[PUBLISH_TYPE_ID]
	,[PUBLISH_FROM_DAY]
	,[PUBLISH_FROM_SEC]
	,[PUBLISH_TO_DAY]
	,[PUBLISH_TO_SEC]
	,[PUBLISH_CREATED_BY]
	,[PUBLISH_PORTAL_ID]
	,[PUBLISH_LANGUAGE_ID]
 from [SETUP].[PUBLISH]
	where 
	(@P_PUBLISH_MODULE_ID = -1 or [PUBLISH_MODULE_ID] = @P_PUBLISH_MODULE_ID)
	and
	[PUBLISH_PORTAL_ID] = @P_PUBLISH_PORTAL_ID
	and
	(@P_PUBLISH_LANGUAGE_ID = -1 or [PUBLISH_LANGUAGE_ID] = @P_PUBLISH_LANGUAGE_ID)
END
