CREATE PROCEDURE [SETUP].[StyleUpdate]
	@P_STYLE_ID int,
	@P_STYLE_NAME nvarchar(500),
	@P_STYLE_FILE_NAME nvarchar(1000),
	@P_STYLE_DETAILS ntext,
	@P_STYLE_IS_DELETED bit,
	@P_STYLE_PORTAL_ID int,
	@P_STYLE_LANGUAGE_ID int,
	@P_STYLE_CREATION_DAY int,
	@P_STYLE_CREATION_SEC int,
	@P_STYLE_CREATED_BY int
AS
BEGIN
	SET NOCOUNT ON;
	Update [SETUP].[STYLE] SET
		[STYLE_NAME] = @P_STYLE_NAME
		,[STYLE_FILE_NAME] = @P_STYLE_FILE_NAME
		,[STYLE_DETAILS] = @P_STYLE_DETAILS
		,[STYLE_IS_DELETED] = @P_STYLE_IS_DELETED
		,[STYLE_PORTAL_ID] = @P_STYLE_PORTAL_ID
		,[STYLE_LANGUAGE_ID] = @P_STYLE_LANGUAGE_ID
		,[STYLE_CREATION_DAY] = @P_STYLE_CREATION_DAY
		,[STYLE_CREATION_SEC] = @P_STYLE_CREATION_SEC
		,[STYLE_CREATED_BY] = @P_STYLE_CREATED_BY
		Where [STYLE_ID] = @P_STYLE_ID
END
