CREATE PROCEDURE [SETUP].[StyleGetByID]
	@P_STYLE_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Select 
	[STYLE_ID]
	,[STYLE_NAME]
	,[STYLE_FILE_NAME]
	,[STYLE_DETAILS]
	,[STYLE_IS_DELETED]
	,[STYLE_PORTAL_ID]
	,[STYLE_LANGUAGE_ID]
	,[STYLE_CREATION_DAY]
	,[STYLE_CREATION_SEC]
	,[STYLE_CREATED_BY]
 from [SETUP].[STYLE]
		Where [STYLE_ID] = @P_STYLE_ID
		and
		[STYLE_IS_DELETED] = 0
END
