CREATE PROCEDURE [SETUP].[StyleGetByPortalLanguage]
	@P_STYLE_PORTAL_ID int,
	@P_STYLE_LANGUAGE_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Select 
	[STYLE_ID]
	,[STYLE_NAME]
	,[STYLE_FILE_NAME]
	,[STYLE_DETAILS]
	,[STYLE_IS_DELETED]
	,[STYLE_PORTAL_ID]
	,[STYLE_LANGUAGE_ID]
	,[STYLE_CREATION_DAY]
	,[STYLE_CREATION_SEC]
	,[STYLE_CREATED_BY]
 from [SETUP].[STYLE]
	where 
	[STYLE_PORTAL_ID] = @P_STYLE_PORTAL_ID
	and
	[STYLE_LANGUAGE_ID] = @P_STYLE_LANGUAGE_ID
	and
	[STYLE_IS_DELETED] = 0
END
