CREATE PROCEDURE [SETUP].[TemplateGetByID]
	@P_TEMPLATE_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Select 
	[TEMPLATE_ID]
	,[TEMPLATE_NAME]
	,[TEMPLATE_DESCRIPTION]
	,[TEMPLATE_IMAGE]
	,[TEMPLATE_DETAILS]
	,[TEMPLATE_CREATION_DAY]
	,[TEMPLATE_CREATION_SEC]
	,[TEMPLATE_IS_DELETED]
	,[TEMPLATE_LANGUAGE_ID]
	,[TEMPLATE_PORTAL_ID]
	,[TEMPLATE_CREATED_BY]
from [SETUP].[TEMPLATE]
 where 
	[TEMPLATE_IS_DELETED] = 0
	and
	[TEMPLATE_ID] = @P_TEMPLATE_ID
END
