CREATE PROCEDURE [SETUP].[TemplateAdd]
	@P_TEMPLATE_ID int output,
	@P_TEMPLATE_NAME nvarchar(500),
	@P_TEMPLATE_DESCRIPTION nvarchar(1000),
	@P_TEMPLATE_IMAGE nvarchar(500),
	@P_TEMPLATE_DETAILS ntext,
	@P_TEMPLATE_CREATION_DAY int,
	@P_TEMPLATE_CREATION_SEC int,
	@P_TEMPLATE_IS_DELETED bit,
	@P_TEMPLATE_LANGUAGE_ID int,
	@P_TEMPLATE_PORTAL_ID int,
	@P_TEMPLATE_CREATED_BY int
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [SETUP].[TEMPLATE]
		(
		[TEMPLATE_NAME]
		,[TEMPLATE_DESCRIPTION]
		,[TEMPLATE_IMAGE]
		,[TEMPLATE_DETAILS]
		,[TEMPLATE_CREATION_DAY]
		,[TEMPLATE_CREATION_SEC]
		,[TEMPLATE_IS_DELETED]
		,[TEMPLATE_LANGUAGE_ID]
		,[TEMPLATE_PORTAL_ID]
		,[TEMPLATE_CREATED_BY]
		)
	VALUES
		(
		@P_TEMPLATE_NAME
		,@P_TEMPLATE_DESCRIPTION
		,@P_TEMPLATE_IMAGE
		,@P_TEMPLATE_DETAILS
		,@P_TEMPLATE_CREATION_DAY
		,@P_TEMPLATE_CREATION_SEC
		,@P_TEMPLATE_IS_DELETED
		,@P_TEMPLATE_LANGUAGE_ID
		,@P_TEMPLATE_PORTAL_ID
		,@P_TEMPLATE_CREATED_BY
		)
		
		set @P_TEMPLATE_ID=SCOPE_IDENTITY()
END
