CREATE PROCEDURE [SETUP].[XSLTemplateDeleteLogical]
	@P_XSLTEMPLATE_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Update [SETUP].[XSLTEMPLATE] set
	[XSLTEMPLATE_IS_DELETED] = 1
	Where [XSLTEMPLATE_ID] = @P_XSLTEMPLATE_ID
END
