CREATE PROCEDURE [SETUP].[XSLTemplateGetByModuleID]
	@P_XSLTEMPLATE_MODULE_ID int,
	@P_XSLTEMPLATE_PORTAL_ID int,
	@P_XSLTEMPLATE_LANGUAGE_ID int
AS
BEGIN
	SET NOCOUNT ON;
	Select 
	[XSLTEMPLATE_ID]
	,[XSLTEMPLATE_NAME]
	,[XSLTEMPLATE_DESCRIPTION]
	,[XSLTEMPLATE_DETAILS]
	,[XSLTEMPLATE_MODULE_ID]
	,[XSLTEMPLATE_IS_DELETED]
	,[XSLTEMPLATE_PORTAL_ID]
	,[XSLTEMPLATE_LANGUAGE_ID]
	,[XSLTEMPLATE_CREATION_DAY]
	,[XSLTEMPLATE_CREATION_SEC]
	,[XSLTEMPLATE_CREATED_BY]
 from [SETUP].[XSLTEMPLATE]
	where 
	[XSLTEMPLATE_MODULE_ID] = @P_XSLTEMPLATE_MODULE_ID
	and
	[XSLTEMPLATE_PORTAL_ID] = @P_XSLTEMPLATE_PORTAL_ID
	and
	[XSLTEMPLATE_LANGUAGE_ID] = @P_XSLTEMPLATE_LANGUAGE_ID
	and
		[XSLTEMPLATE_IS_DELETED] = 0
END
