CREATE PROCEDURE [SETUP].[XSLTemplateGetAll]
AS
BEGIN
	SET NOCOUNT ON;
	Select 
	[XSLTEMPLATE_ID]
	,[XSLTEMPLATE_NAME]
	,[XSLTEMPLATE_DESCRIPTION]
	,[XSLTEMPLATE_DETAILS]
	,[XSLTEMPLATE_MODULE_ID]
	,[XSLTEMPLATE_IS_DELETED]
	,[XSLTEMPLATE_PORTAL_ID]
	,[XSLTEMPLATE_LANGUAGE_ID]
	,[XSLTEMPLATE_CREATION_DAY]
	,[XSLTEMPLATE_CREATION_SEC]
	,[XSLTEMPLATE_CREATED_BY]
 from [SETUP].[XSLTEMPLATE]
 where [XSLTEMPLATE_IS_DELETED] = 0
END
