ALTER TABLE [SECURITY].[FORM_ROLE]
    ADD CONSTRAINT [PK_FORM_ROLE] PRIMARY KEY CLUSTERED ([FORM_ROLE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

