ALTER TABLE [SECURITY].[ROLE_USER]
    ADD CONSTRAINT [PK_ROLE_USER] PRIMARY KEY CLUSTERED ([ROLE_USER_ROLE_ID] ASC, [ROLE_USER_USER_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

