ALTER TABLE [SECURITY].[USER]
    ADD CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED ([USER_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

